---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-k8tz
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/k8s-tools/k8tz/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager
