---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app glauth
  namespace: security
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      repository: docker.io/glauth/glauth
      tag: v2.3.0
    command: ["/app/glauth", "-c", "/config"]
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "10.17.8.6"
        ports:
          http:
            port: 5555
          ldap:
            enabled: true
            port: 389
    # podSecurityContext:
    #   runAsUser: 1000
    #   runAsGroup: 1000
    #   fsGroup: 1000
    #   fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        type: secret
        name: *app
        items:
          - key: server.toml
            path: server.toml
          - key: groups.toml
            path: groups.toml
          - key: users.toml
            path: users.toml
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
