---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app glauth
  namespace: security
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:

    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

        containers:
          main:
            image:
              repository: docker.io/glauth/glauth
              tag: v2.3.0
            command: ["/app/glauth", "-c", "/config"]

        resources:
          requests:
            cpu: 50m
            memory: 20Mi
          limits:
            cpu: 500m
            memory: 50Mi

    service:
      main:
        ports:
          http:
            port: 5555
      ldap:
        controller: main
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: 10.17.8.6
          coredns.io/hostname: "ldap.${SECRET_DOMAIN}"
        labels:
          io.cilium/lb-ipam-layer2: "true"
        ports:
          ldap:
            enabled: true
            port: 389
          ldaps:
            enabled: true
            port: 636

    serviceMonitor:
      main:
        enabled: false
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    persistence:
      config:
        enabled: true
        type: secret
        name: glauth-secret
        globalMounts:
          - path: /config/server.toml
            subPath: server.toml
            readOnly: true
          - path: /config/groups.toml
            subPath: groups.toml
            readOnly: true
          - path: /config/users.toml
            subPath: users.toml
            readOnly: true
      tls:
        enabled: true
        type: secret
        name: glauth-tls
        globalMounts:
          - path: /tls/fullchain.pem
            subPath: tls.crt
            readOnly: true
          - path: /tls/privkey.pem
            subPath: tls.key
            readOnly: true
