---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - tls.yaml
  - hpa.yaml
  - secrets.yaml
secretGenerator:
  - name: glauth-secret
    files:
      - server.toml=./config/server.sops.toml
      - groups.toml=./config/groups.sops.toml
      - users.toml=./config/users.sops.toml
generatorOptions:
  disableNameSuffixHash: true
