---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: glauth-es
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: glauth-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        glauth_groups.toml: "{{ .GLAUTH_GROUPS }}"
        glauth_server.toml: "{{ .GLAUTH_SERVER }}"
        glauth_users.toml: "{{ .GLAUTH_USERS }}"
  dataFrom:
    - find:
        path: GLAUTH_

