---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-local-hostpath
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.2
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    csiDriver:
      name: "org.democratic-csi.local-hostpath"
      attachRequired: false
      storageCapacity: true
      fsGroupPolicy: File

    storageClasses:
      - name: local-hostpath
        defaultClass: false
        reclaimPolicy: Retain
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: false

    controller:
      enabled: true
      strategy: node
      externalAttacher:
        enabled: false
      externalProvisioner:
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1

      externalResizer:
        enabled: false

      externalSnapshotter:
        enabled: false

    node:
      driver:
        extraVolumeMounts:
          - name: local-storage
            mountPath: /var/lib/csi-local-hostpath
            mountPropagation: Bidirectional

      nodeSelector:
        openebs.io/storage: "true"

      extraVolumes:
        - name: local-storage
          hostPath:
            path: /var/csi
            type: DirectoryOrCreate

    driver:
      config:
        driver: local-hostpath
        instance_id: hydrogen
        local-hostpath:
          shareBasePath: "/var/lib/csi-local-hostpath"
          controllerBasePath: "/var/lib/csi-local-hostpath"
          dirPermissionsMode: "0777"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
