---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-problem-detector
  namespace: flux-system
spec:
  targetNamespace: tools
  interval: 10m
  path: "./kubernetes/apps/tools/node-problem-detector/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
