---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redis
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: 18.6.3
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      enabled: false
      sentinel: false
    master:
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 10Mi
        limits:
          cpu: 250m
          memory: 100Mi
    replica:
      persistence:
        enabled: false
      # replicaCount: 1
      resources:
        requests:
          cpu: 100m
          memory: 10Mi
        limits:
          cpu: 250m
          memory: 100Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPU: "75"
        targetMemory: "80"
    sentinel:
      enabled: true
      masterSet: redis-master
      getMasterTimeout: 10
      startupProbe:
        failureThreshold: 2
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 10Mi
        limits:
          cpu: 250m
          memory: 100Mi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
