---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - "https://github.com/sbordeyne/kanidm-operator/tree/master/manifests/crds"
  - "https://github.com/sbordeyne/kanidm-operator/tree/master/manifests/operator"
  # - tls.yaml
  # - helmrelease.yaml
