# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:5+Pm9U5lFaua33XA7z/4RjZmCMzFckASuE/gBv6boP1mVXoQ9JNxYtDAYOqoEZCTU558/aOBr9GVA05bYBBq1ct2pG+SFnpVZz/PGESPv0qpBPvliy/yQZKblVNP0KFt9SrBnVegMdCxre9TplOcEyESXmn5/eJDJJlqNHdGZo8DJSga4dcTTduvwMt5IbfwlAWF5vflFzuF4twQ7iHUAD2wRSX5RGDt67iPXaReALffuHYnBA==,iv:TWvw+FE3E82fFXWu+MwmJLagt0LP0DoVMqZvSG3MCXo=,tag:tJJ/4VN9sNi8vcGTcMFCWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z0tZY2lLYmFCMFBVNk1F
        emVMRTJwbGFiVDFKUGFMV3JXeFk2bVNOc21zCm0zSWFHTHZ2T1R1M0tDS25BcWlT
        eUY4NkppdjlvV0hIWGtRdDh5cldJNlUKLS0tIFhNVk9KKy93bUVKMEV5Z0ZWUnlU
        L28wMHRBZzk2bFNtd3Y5VW0yTVUwQ0EKdTF4kAkCdGdA1q8PimeDPbcOgNL0QYTu
        XZN2BzoLHIEQF7vRc3aY6219Durvq+7bxfDjjnhe8E1niSibeHx6VQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T18:37:07Z"
  mac: ENC[AES256_GCM,data:bEXDbmJlvMMVAScfJMd6rxDflte/gQcdJypuc5/meHeiqt9+y02MepLVJUzq9pG9ic186L/n5aQPBvlbN0k3EDBZ3aD9Zf4Cwv5pWswept+Ii8B0u23mMMlXJhXXJkYUsbO9ErKdMmySqBP7ZmiCghWxTtPnGECIrA02+4A3184=,iv:4yx005qT4gDnYPxuG5ZdFbQulX151sDMDAhe+KvKoC0=,tag:LGTDNMlfQDePnmzbLPtm6g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
