# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XFlknzQ8XuBHvdBAhtf8WBEWa6lzgdAXJD3SxBIokJm1FBHkwd3FToNRCJJPKCUgAz8rbBHFU2RikbyBkRQ5px5RCNSNMcmwOJq93Hf+nPwNc/pOTEuzmK9LqZfXD04U/Ndn/DU7PRc1qYmfWCfW7RY2pRigXjINFHpmxqFCEwWMl6c9lKlVOdTc72WmufcUol/wNmJJXzd8W+ZZkWfaLMTkYPtTJnBnPFWYkQDQnCvUb6gSUg==,iv:3nrapenc2whwHWGF6xLo6A7K/kREodgkJXDr+jJzyHQ=,tag:8afIOa1HJ2cUYJHGo05pKA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQmNSSEE1OFZ5RlBFSGpu
        NDBTcE1tWnlHNHNCZDRDOWhkajBuMUNlWVJRCm51QjVCU3JsdEhjZWl2Q1dpSmdM
        OXNDVmNrODFsUXBrOW9MeXFISXptcUEKLS0tIGpiWUZGODQzVFFDSVhRM29vQzZD
        TkRxSXdITzVjU0xmVldicm5yZ2tGSmMKi/Zxhc7qofjP/BocTvGaSpiBFHlripKI
        XrVp/2bsHZayg0YTwnRti7OXkcoX1mRzrEvKYvKJy1rdVtr8bfPCmQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T16:39:33Z"
  mac: ENC[AES256_GCM,data:Rh/WXjITNWY7OckUjPXOFAQQ0kkXkspn1CDKFYxeYib2bCmkLvcTeg25wBEsz3mT49TEfI/n173fcgZKvYE9CiB4qXiKm3P/p7n79P7AiY5WhOF03tPld69CqDIrKFuEa2WJBt+CTzmCQLxl3nhmH/D85VaNaXMW0mgCkN0tiG0=,iv:NeLNaH3dQIMNoyG9LkXaDSF2iiKBv5PBx11P0sRP+zI=,tag:AbdOIfJU2wEDVjHdAxDiIA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
