# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:T9q9hR+KmPGy9ogWgcv+v2jm6Iic46fVxosQ6losSKJj747Q8ouAPW9A9jm/ernmVAzx1Mi3toXqa6nxSi9urmCQUawR8bcC2pFom3QzQLl0kH/QoxexKz3/hy7QCZcNr2f+9cJHpVtVJrrV8a55xhtZu7+pLZ+jv8un06N48XFsMLDR4mSo02+ZOkBO+UWkzIGHzgbWQSrQSPoeN5c+jkkIUwjXOcUfJNkzLR4DjXXOGwgiNQ==,iv:/RDVDtzQtszBpLvL4DKAyfdw3zF/CkxKlJm8WzeP5eE=,tag:7J2s2asD8rPiNy0cEvLOCA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcmEzMGJSKzdXT1AySkZM
        MURNV0JkSlRGd0pML0E0dU16VGNWSGxuSnprCmdnTUZUL0x5NWk3U2JuRXozTzlH
        TjNJMDFJZGE5alBoRityZVlmdmdDRlUKLS0tIHNFQ3I3emVoRDBvS3B6aDdoVzln
        cXV0SnVLM0pJMTVnNUE4aTExTEFUYVUKOo8DFZyJIIF1DE9FF68HDb3Kz5RaDkre
        Vs67R9ANGsexVoZKqtKS2FQeFRyjDwpdyms9lpg9sc4BJJueAeoraw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T14:19:11Z"
  mac: ENC[AES256_GCM,data:Y6rnzDTrqRS7NaEkbp4c9BpdvwMcCVMyyzKI9yXuFTup0bEamNYggFYjZImQHEYd31Kq1K/91KRiTXGqDUYJDx4JwGLYtGOVnyOrpDMFdxk6oZQYAm4+9Ub37hSzIY7WCCgnZF4d26+DU8d+XYRZkMEk5h4D0D4lz04jpiH2vVI=,iv:zcxIyag5LpPFCiCHbO0W4LUVGt+tiv/Aalqyj6z9RxQ=,tag:28lB8aJfHBW2hY9z9yc4KA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
