# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Qyv4Q50awsdvzZresA6pAsm9bPV8TN/KHwxwgJORIbMhDUo78SOy3zqW9rowod1j6wqdZzPYcA2iwG5W9F49ciAgZnPSrVR3VEvqoBssH8f2fc+TObLTfRasnnNhJCzeUMtvbJ8l30jA2pHLWpBVXNRFbumsxvkYa+u9gIiDsAaAF45g+Ju5HTveNN/CQcXGhTLOqZ7d4jr5luY14UfXwGusibMzv/xUJO0uX0B+oj6gohDdtA==,iv:kctwFIAFYaL81AMiYlIzDZcSmU5sYZqzMopkCiv5IQk=,tag:egVlFCAq5hCvG6MwMVeciw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUTBjb2xUVkN5UUlMQW5I
        VXFNODVkeCt6cGlPSXF0KzhBN1NZK3dMK1dVCnJQRnBnZ3E1QUtaU2V1RWJ5RTA3
        ejYzb0R5am9oZjJmQngwVWFERGptNmcKLS0tIEVEeWtOUVFxTm1iU1NlNEhra29w
        VkxaNHBMWjNrT3BhK2RvQ3NzYkZYUlUKKPHUEC36cC+BdBG9oV6FMUozSVeEKz87
        IRUDFqXOmEWiyB5gp3QZT+cv0l7x72HQaFnjtvGFdgWt2gJKgLxy0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T21:32:18Z"
  mac: ENC[AES256_GCM,data:M+ENtp/0+4/YKYhWk4GA0Cin/6RT2IkHlT6EXHPSQvCUYZI2BfXg8qa990dnzDxoyOb6olVIprsvuVXr37arQPmFThgElH0tG4LKmaAemQjf2GarAcWeirdDeLcEy770IGfmadHmsvvX1528nnCusZvOjVjhSjReeljpfFdUWLs=,iv:zXI2RMktMLU2On7b50NOpsj8IB6Cl/JBTbCuZdn2lJY=,tag:2m7Elrd/fH1c99VzKgXB+g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
