# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:jZqabhgcBbAOsAyC1GSNV+lTukCs4oynSkn61gTp2GBltgI1In13IMbXWyqrV1uEZ1VIJTRTHfIop4uEj9LX6TtJwHtycciZTjA3Jp5V9erxhpne6Gi9OveNS5zXnStKWKiYijFTcOHlEV7sX7GN3S95vn7wjNoHqQ0KArqIM473OY8y+Cx23sdnv2s2Af6w4lMIyNqn9asnGhu7RU18liLMkTG0hU/3B1DPoH1+iUB9YxnfRA==,iv:il/pqxxm1E1nmQ977h0L+zm/iLT1theMEOg5+4umt3A=,tag:8KZVFCmFP8QJ7aQBe9OpXA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOXdoQmMvUDRZMWJtTDVk
        VnVjNHg0TXlwOGRlZVlQT0JYa3ZQV1QzM2tvCmljejRsbjZjM3EzR0x0TTUrSmUx
        YUhLV01Nbmg3S2FWK0hZeVRCRHlxK2cKLS0tIFdzWDRudVA5bmJ4bmRGSStLTDRB
        b1RId2FTL1NRQ0FGNFd1em03VVdFaFkKoscSDJgc4Zqn+HjR6IzO4LuWLSP78k3L
        6447AD4YmxctA8XStnTCyGESOQ0SdfXrt1w7v7J3NnM/UVnMDEbOMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T10:32:15Z"
  mac: ENC[AES256_GCM,data:nYQxc0cXPzrTqf/0DLGLTUDIB8NL3UsGqujXI0dEYWc5RmncJDKN1O96LkOCw8EzCVx/QykgVy0GMp0sDdH2kBgY0cpWBTOJVZiOnQHKa8dPhtu3+mZ7Fc2mr9lBASmCj8xz/4NBmeXJ7r7GXZHpXCSdHIeeWEdqCAxgF3ZeRG0=,iv:MPJ76Bma9tkRqWHjBE5vYGZrxSgdgC8LBEgenk64DP8=,tag:FxTkcBPDF57JTUMWNpW8dQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
