# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:EJh2dBsaSC4VRHhwZwLMXUWLv4zwh03qIwEzplTdZkaEFFRqtPYNffUt/W1FCc5yuQmhqf3Sr/B8pfexBuxJDlie9VwNW4YXZtVOEfXbNgqe5ua1imalVs7eZQwodZ276ABVFbtSMkAI80fmufxaXyLSYKJi638NKaOON5y+kIw6s6zLMLBko2w5mXnVfkoC8O4suc3/u5LpKYKE8DHIv6Fcv1tcfWToMWqVkGpbUA==,iv:tHRAJ0Dnc8pofdZv6pZHKfBOX0WKqNSD9k2AfrZMGTU=,tag:y9dKTMu+lbihl2NMo9v4zw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVVhHK21UVW5kVUpKMU1G
        bWkxKzF1Q1lyeVlVSHZxQ1VTQVJ6T1NHdHpVCnZFOXoxTlVIeTZoZFNwZEEwdHo5
        QnNWWk84bmRURFFtTWY0dkNSb0hnUTQKLS0tIHNDNHM0MDQrOFdHRnhjcWRxZlQ3
        cnJicVNBek1Nc2lGOGd2KzR1SHlpNmMK81MOOj4kIt5EBQK0TOrdAYMgucQkJrPN
        5OQBtcEzKT/CH4LLVxFmjGnP0MC8fumXrQNfKHmemGRRxtVwWIDm7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:19:46Z"
  mac: ENC[AES256_GCM,data:Ud+CcqxMvtgEN9Wb6yKqrBexvYvjwoM3eY4x1fLcOgJ5M41Ky+l66fM5tNin8yTtleTf7cx8VfU+tpT3DOyMU+F9jgUnErMfizLH5tsH3v7lH/wpYFcZuL1zKNz+qVWEqVpfRGdkILor3o3Yk8CWz5L9l3oum4Suae1MJBLSIHw=,iv:L1sq87UgtUJounKg3dJN/cDt+zVjqgkzpH+ZenIoRJo=,tag:TtelbuBmvKpcnPxLxdfQmg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
