# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:yA8eaC1cKwOQ3nZ4dy+6LnGUB4rDX2r9LePgLUeBdTUmTaPPjdYBOpnRBug2C2kRaERrQKH6jqqCNqMbX7bq1ywgiClkEq/97VqUj04bf29EjmggKw/H8Rg4E/xNgPK74sO2rM6GwI0ajYK9NuG0j8Jw/Q+tYGlhPKQ6CzaTIiTolgR/odd11jJyWWAJX/iEk2T3PnqioHZLGU0UZOoa9ZS41XXt4vY/8ETVSOZBmA==,iv:QrBUaFv0c/YMRNS/sLyeh33vyQq0a9ChW3BlXPTRKTs=,tag:lvAs6AlUD5rRqGrVydMz2A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGekxnTnhxVEJTR3RkQk5E
        R0lHdmRCcVJYM0ZOcjNSLzB2Zzk0eWdSNjFvCm1GVWNHODdiTTJpMXovRXpkN2VK
        OGR1WVFMVUtaMzQvYXVkWkhGTDJHemMKLS0tIFJPT0N4OHQ4MHo2SW51TFJVUHI5
        MWlwNElzOUxqK0dCaEJzMmhLaVlqVG8KAKsi4CehhSLdX5DLfugrB1h2Nh1y78Tg
        2/SWpeYUoViCfVsyXjm0nFZCujS9aSvBDV2kSZK3oq9FYLmJgzzuRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:37:12Z"
  mac: ENC[AES256_GCM,data:rmOH1pgoKO5go97YZ1T8W01Y6iaw7m5OIHAwDEmFK+vXGpFfmZkQa2VMHIL56LiWEadwKfrGBw/a3/YEptH/en2qJ9mLf9DTBOixEPcjGBcHM1KW4GwphtgTEFENeyxA76VSGTphD9qySleJqfVyGSnGtZRKVNE1tv9rSpWOo5Q=,iv:Cj9M5Q2sTjb2hysGHsnk2Sss7TkjgbGN2+/2GTorzFU=,tag:6PPXLkeZH/eUZzZmcnbmbw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
