# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:/+lkYISx0P+aAQs8jjcqgvkhwexn7QtGeqCJB9fzZ006oJt8768WyDxK/HFv8yw47BU84ArdhaluliCXCpQa7mYjSoPDyGJucU/mObRSCUK/jvxRy7uByeU0+YjHcwJeG33z1VtslITRDVadHFQaS3zO78f52DV4Rh7Xtd2ImJcXVWA5lmBOap4FHsfOrwxAG/1kprpnB+ZpNPhozVzLrdFEERKi/TYBPAdj5WZO1C/kc2Ht3g==,iv:8AP7wyisOhb7A3BFGIo2jdUvOlzaMpPad0K8K+aJnCU=,tag:lLW1ZeUK0m1lyeAUyQoKBQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMktoMjlnSWtISVpVS0Ri
        ZWt4aGZpSjBzSnJzK0l5cWtvNEkvS2s3cEFFCmlrRUJCNko4VWhNWGxuSVYvWE9Y
        ckJlRHlIcllUUklGYkJFVnNpdlhTM3MKLS0tIHI4cGhra3lrVXhXWmk4T3pXTmxa
        RFB4YzVDT2VOSjBEM1kzdTE3eEpub1UKbuFzdCHEnEBtGUKRqd94fKqHKwzhDUKl
        wu53zLx4x3l6RKQodNymjOm5nFEK/F+uxVXfrVSoaT5EZfgoDZNw/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T17:10:51Z"
  mac: ENC[AES256_GCM,data:Qpf7WAfbSeU3JI1+CaTxB8/Zt2vrsGAL7nWwI5E2zrk/cXMkIsIzlvdn5Qq/YGCBzE/VlSZZcPs0Aa35SQOI5+MYaFRsWZL/7+s5WYRsrM1xCxV53YaBUhZ0zM8YmAKaCSog+gbezgO2PmB282y+fW5IJrdcFgQHnZkLGLpDavA=,iv:iBRq5sRmMI4KeS30tzbmQ6JxcL2TK2hgddrDHqPoTtc=,tag:nvXfo0bhkJoKRxiYQtbhAA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
