# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:v51cBhEvq/JRaLz+RP5DnWFrnip3lULdvOT7wqf147qZiam5DaGzuIOlLS2MAd2QDVUcWnDlZREkPTyPRaWaFPnzsakkuVyY4Iy59KIljOu2gvprxIdpLnPZBjLDpy1m0GMrFaAf6Fbe+VKj2uWnF1+mmnduVXG/l28xi+6zB4duqg5h6nMiwz0TgeMcDv05oVlFTzHg8OzhPu7ZzDM8igP+WC4E2zycuHBoS8iMEA==,iv:80+UstqaSBdR6IwutG9D1M2GGiepqzRJiXhh7Oi4XGE=,tag:Ql+mI3pfgp1DX95VYAFOhQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUXp5MHM3djV5d21lbGhj
        OE41WExlbFI0M3E2aFVLcDVxalo3U1JoMlNFCkZxemVnOXY2b2NldG1rKzFBalpz
        QW1QQTNVSXV2QWVRclRpeXZybGFIcFUKLS0tIFBIaXc3cnU2bk9MRXJpYzU1bHVp
        dFRGa25WOVRXQ2JTcXNUQzRHSzNBbGMKSdhkhQ4AmHjhP2axUphB9s4O5qtdRDwf
        NBk9w73Ju0xqIOf5NjiBWF7O+OG+DbpVbfO24DqsZXklqSbA2uZgiA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:09:48Z"
  mac: ENC[AES256_GCM,data:lkoTN/ynFfTywHgyRbmwXyK7C2/HL/fCRbJX+u9sEJr8X6j3kQXyLnAUc24t+WMigSzBKvSoq8fZMDiaolSMDNb+tXZ+MI28aWekqQDjOiQNU86WtMjDuPcazA+lVfkavL6YJsDluHOSuLrcn+QJAewOR0xj6ejBb7oa/UjOpa4=,iv:WwXryxIEirRS1GJ9HWiEeGMgyeSzufoRDm7djjqWkJI=,tag:ArJWk0Ynz2AiAd8FYiTF0A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
