# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:WLGH4jIwYcX0Ph68IRvNXzvmUg1ScaoW3yi6lvclt1snCCOoUdWdfCQLvLOy562nLXCBuMbU0DBDwXq24d5ys4De1tiFJNjIEJjHzdmD6FvtUopVfBkBUuNirK41Rm3FX758gjinAxv+RJURVKvQ/luSMAK2wmBGTeauO6bSjEWZSaVrVvtd2aUS4MudSoJrq+2iAQZNpyzXWyjNFyAp5tsU94Ycsb1UtSZoFH+JWg==,iv:qS3R6YUesKlYief+QuhI8mTyVrPKgvK98p/TJeOVS2g=,tag:CuBF7P9CPAU3elyID8wH3Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT29xaHdDUnNocVpCd285
        MTdqeUFkWVRrcXZ6dy9kQ0FCQk9SSHVvV25BCjgvT2RueURVZFJSSUhjb1RvUEtX
        bEh2Nkd0b1ZRR0xIOFZpMWYweU5Rem8KLS0tIE8vdmQ0cTJGV1R5U3NHakFlOVd3
        SXhJdkoySVJ3UGhqekNyMGY3dnp0SjgKh0HyrX7HZfFX/X0jEKnWm6RzDMFsleCk
        fNMMhWfq2AodFKowce2K/JI8yFS1RxNq27I1tRAfTBzU35VGgbHP3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T22:41:37Z"
  mac: ENC[AES256_GCM,data:Pu4v7ivbowV+VxeEoZtduazmMekoJx89CASQDgSXzQZ9YVCn6Fv67sJ03TZoTHYnSOBx5GbP/zaNiIoAKflOV4wuSJ7En4HbTE1ky9V0uASFys09x0/GyQK/esrKthNswklxK8tkatHmk/stOGSLW1raB35sp7Icdtd05UhORtE=,iv:q48VHNRfbOHMX6HzD/dyW4wnI9IYaRuhvXCZgcRMF8w=,tag:jazZLyQ049RjDkA9eqm89w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
