# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:tBWZf6I3EmJW7NY4px2BBtVSTe/1X5UQQlmA96K4C0DgFyHGLlnldxU8/Avdnf39A3uBsg0SGGLewHZ+lAL+eCuC+uc94NXkRr1Fs6C72CS1ZTrEHPUc34xuYPqUv9lH7KN3C9EuQ+Cb9h/Uyytna+HNQzwXxmZCPsAL2hSD3AX8r1SPZGorbDIoF49p6i/iziOnXcA8JqA9LJ7Yfhn4hAEIIk/4Wz6heK4guKqZ8w==,iv:cW0a7hzR1FdH6Yiy3fIgKQP/MA6xLzzz83v+ESmEOSM=,tag:hsH0kWLeEGlvr2ez+GDDEA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUzR4dGdzNG9sMVlzZFkw
        MUZSeDFqYld5UFoxMEZ6N2h0WlgvdUJJZzA0ClJYeWhVdG1rakIyQ2Y1QVdCRFNn
        NTUzMTdRVXc1aWVGZW5Rd3JaY3FSMlkKLS0tIDlEdVBLK3RJcnBmZWVCL3RNUjJF
        NHNYaVo2OEtGSmxhVjNJL1VJMnY0VEEK+ye7ODUU3L4zIXkvx0J0SEdhC1ApFzV5
        8tFPDoNChTC/vVUf/xDU+z5O+YJugyO+s4c4TdOpNtHN0bevXm3G5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T15:20:58Z"
  mac: ENC[AES256_GCM,data:mdovb60FmO4xoD8f0zoIrPvui24/fcWT7y0gjAkiazfmaiP7PWAikuw1xi0Sm+XV6POQfoIn1MLMp99Fo/Iq6YVXnXt7jbAuXXf+g87PECJk70fkvT9hIkupUiLzHDwyN5Jd/C+eaf8la8eANfpX8IFcULZPNfYl7oHZYcyscKE=,iv:Upd8+QPbYABZpFKotRAyWsryhnuI2JDRf11z/zv6uyM=,tag:KKsQ6+rKK336TsGYtlonXQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
