---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app searxng
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx-internal
    - name: redis
  path: ./kubernetes/apps/services/searxng/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
