---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-02-06T21-36-22Z@sha256:1f5e263a492659da3b5c165eeabe70fac1c186081d3fca6863fdc48c3e04856c
      pullPolicy: IfNotPresent
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2023-01-11T03-14-16Z
      pullPolicy: IfNotPresent
    mode: standalone
    existingSecret: minio-secret
    # users:
    # - accessKey: ${THANOS_S3_ACCESS_KEY}
    #   secretKey: ${THANOS_S3_SECRET_KEY}
    #   policy: readwrite
    # - accessKey: ${CNPG_MINIO_ACCESS_KEY}
    #   secretKey: ${CNPG_MINIO_SECRET_KEY}
    #   policy: readWrite
    persistence:
      enabled: true
      storageClass: "openebs-hostpath"
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - minio.${SECRET_DOMAIN}
      tls:
        - secretName: minio-cert
          hosts:
            - minio.${SECRET_DOMAIN}
    consoleIngress:
      enabled: true
      ingressClassName: internal
      hosts:
        - mc.${SECRET_DOMAIN}
      tls:
        - secretName: minio-console-cert
          hosts:
            - mc.${SECRET_DOMAIN}
    securityContext:
      enabled: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    # metrics:
    #   serviceMonitor:
    #     enabled: true
    envFrom:
    - secretRef:
        name: minio-secret
    buckets:
      - name: cnpg
        policy: public
        purge: true
        versioning: false
        objectlocking: false
