# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tczQDDnaJ9rY1Xk9SEQYu/FL3FefCM4l0WLxexXaKCrhChNoI0/I6Q==,iv:WavRmPAsJMhtVUWE13peQocH/lwPHYoTBk1OvNQaH3E=,tag:btEqbU2igdGo693/ABW/ew==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcmQxMEhXL1dLZkN4S3BS
        SWhHNGtBc1JjVGNSYnJ6YkV4VytoSVNDNVhNCnFZelcxV1VNaktDeW5JMlB1SEZU
        U2g3VkgzNEkyRmhPeHRNSDBveUd0aEkKLS0tIEY1cUVpSy9pZGw2ekZmNklldG1u
        SEpDSVh1L0hXMWtEL3h6VVFseTRVT1kKt5ifRV3g6l9YhMKRcZmjnAkZo+VVNsMK
        E22jZJrGFGeKjkshuNegPbEgnDXBDVYEWR9u80rqwXrquyoeCZQEcw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T21:32:18Z"
  mac: ENC[AES256_GCM,data:v9H6SgmJEz8F6jE18Jb4bhiyVIHmswIxzugf3/wsvgSTcvdiG+ZHCGkqwqrNj5ayRtwUfFT+Q9mwf7vpdLoYDxMiZzXqHV/UkhZ+QamIPPMoxj/UR5MZSYDzICRD5DWQqQDpxwwpqvHnprIli2fi7DTYKvOx2hl72LN/efhl6fo=,iv:jdm2R0U2WF/BLJK5mbUeW0oNlTyGUMtKDd52IGUk3Bg=,tag:uejUjlx6Tto400wd0wiixQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
