# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:xdPRZ4wk07LHQn+vGAl7gOS3wCr5IPsoOdPE/d/DCOSo8y9mhBSfAw==,iv:tAOGrSk4zsM4G7hip0pAH+HLoWYar/KSrVYQ8fLx++4=,tag:rRxzlU3HiUQKH6/CtWXa7Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L1I1VjB2K3MxMWpRWFNz
        emlQMkF3ZjhKSVhncDlOYjNIMXlIMTFzcTJ3CjBBT3EySE8wbGhxSEJLMVpYR2ZP
        MnVmK203RkNjS0lyZTE5bXNabTgwZjQKLS0tIFM3YUc5bFZuNmpxZ0ZyWXh4bFpO
        SUlBdEdrV3U5R1dWMFBZbXh2MHJiYkkKK2u4QSEtzPkTJy7vi/HafKVHZHGI+By+
        SVLVMpyWQCDazQfnXKJzkQo2zlC56BTDBCjeyoEefdonBG/qaRZ5sg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T14:19:11Z"
  mac: ENC[AES256_GCM,data:CsZLY6VBneeP7rUJvV+IF+6J3CqRlRU2/ZxVUSHeaesEFXMp2pefvPeuGNRvEm0IAexLVjNlA1ROoxeu5JzwbGcDOt1vkFTU2ZUMmHLXgqaKSS1iEJOOn/OayTGgCpxbpxlgL6V+EVCScOi7/XJzVtZc0f/IKDUUnbzDUoTJpP0=,iv:0BG+tzxunhiN7nGV71hjsDqoGLyImzM8ubz69wsUu/g=,tag:2TsA+oSSAa5sBTHZVYjrJg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
