# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:5B3Kcxav5k+RgIiczdTCmwMUqFykbBgn5mTVXHZ4hWDoSUJqn9RgfQ==,iv:S7dayiLmVanT3d1RwqjUMVtz+wlPnIubSdowGhJCAKA=,tag:H4ZD+InQUEv348368kJqMw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNE04WFIvdWY4ZGMrVllt
        OUVtTFZiNmxSTEdXNFdmbHRjQ1Zhd21NZzN3ClIybjJtU3hsY21uVkJrcWVvSlky
        WUV6WlBUZitZYUxReFdodEliekV0aUEKLS0tIHB3ekJoZGJmdGFBaFhIeUNZVmF5
        Q3IvaThlSlNVSDE2ek5QUUNXcVlkSncK2f6xkFaZdctKTVuJoBRAfwz1TnlAQrsm
        AZSpr8DprAlX4axBq64rDy20obqcCxFvlRyfm1ZVKnylDzMrS05Fqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T10:32:15Z"
  mac: ENC[AES256_GCM,data:Y8np8n69EeYmIF5zDVZPYrSgxe+umXf+6FwGnYB2NVdqbiOd3KMnL+waFhtaU2SMmo/nOf+8XeVr1tNveU/XKX8r0jOz9f3BppP2fLaC7GIsV1yAXZrsridQytEuLEI3uBculLX6G/dCuHFLE51XzCgwbbV5mPIHQK22sbhWd7o=,iv:Mehj3JezqK27rQYKQGnV2NJtZj4iNu3D4x293bpyKig=,tag:pjUicYYDz6lVYtmm9EQJWA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
