# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BVh9XaknHeXh1VwzlUt0dbytZQr0TGvAWVeW4RHD5Go4TMqex9IfZA==,iv:hKp7JgYIhvxsDlHV/BA1jMGnknsq871wjMLlrWhSfh4=,tag:g5PTIaKItkim3FPe3voAjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMkRxZkJVb29rb0Z6RXVW
        bGpVczRSaVc4amk2dUJTQlVEcE1UMHZ2ZFdnCnY0QWswUjlmak9wdC91bUdsei9W
        WlhOcCt3NWhycDB1c0xLSFZTTy9JWlkKLS0tIFpPbDVYaGJVM29qZVhUQnhSM0Nr
        K2RHQVZneGpxT1hjQ0lzVXd4S2VnU0UKy0dlx/1YxBKI6xKYqRAS5HDurX2bWue3
        UdZbrfYWIkgwddSEYOST0lmits8Q4Y8TCbsiJX8xRaJe1uiF+vonbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T22:41:37Z"
  mac: ENC[AES256_GCM,data:h4T+tsRi4OW+TC/mtRJ8jMIeNJ+fdukWosVgkYIEm4XEgtui69gi+XfXmAItoC04hNgOrWRscAscHrY7y7HlQfrl9sdjXJuPbB4HuONQmH3dzkyiv1I3VEJpZzbPTDqO0jmltNMcir7VffgUFzH/MRKPp3oFDnhb9GQ2jVWpgQ0=,iv:1mb+f+99BWGS4sgH7r7N1VXjqAAqL59I2k+PCooB5/w=,tag:CHf6qOM/3akMzLGlHJNZBQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
