# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rsxA9FiLchwzUpu+xFtMenFD3+RFstyFsw6ddyK0Zsi3I/QJJSzmNw==,iv:pTHj+h8KyCSeF/8Q7Ir9xzSvAJhCQ1NxBHF7AmQlgFY=,tag:9PxFCZEmDF2Oi6h8MmEHdw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTGJXMnJKZmlNR21RUXRs
        djFNbVRHdkFnNlhkSU53dms1LzFQZWJidjJRCkc1a2p6RnlWakYzSGNYK3d1Zlp2
        UFRnUVhQZjF1N095cUgvWWJGN1FHYTgKLS0tIGNUaVR5bWU2TVYxOEdMcEsxUDd0
        SWliMDV4alVhSzJVbDZvcTNXZnUvM28KVlgLgGcYwAfrH98WAKtfWtDjL2gExpva
        k0ChhVCAeTRSY7YTf2j1XLpsC4P/zp274uu4C+ztY4qSgmJUQMrrYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:09:48Z"
  mac: ENC[AES256_GCM,data:CMf9Iv2ku+Oe6GKkNVS7ksNsar6xoskzUT1TpWfVPnUJD4Oi0mR7/O+SN3/LCZncF3efE8ZK7lHe2PYovK7Tt4ts0qEOPt5CnABfYDn4hsjCxHOUSdN67uo5K/xZqT6g5h1G+HC5RrnFWAiC5Fi4WjrUJJUs3P/7YP+eBc2vskM=,iv:poFGFkuGfT6hMmG+FQQxR47rZeYxuxk+bq6HgklKuzw=,tag:4JM1lRGY1drxlhjGfYigvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
