ansible_become_pass: ENC[AES256_GCM,data:2mdLF1tHH+MR,iv:sfC+kRc/8rLGCKI5998O7NKGSP9S7pTsECJxEZfGB50=,tag:wseIhhQI6mzgjbQjdXGJxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbEpiZEFTZGwyLzkxcHEr
            TXdlUkZ1dzM0M2VpdjhDSWJvSWZRVGNIYWxzCmN5ektrSkc1eW5VbXdzSmFtVmor
            eWU2VlVYUWRVWEg3dnNmVWhpT1MxM2cKLS0tIGw0cGNKNEhubDNnRmFwMjNScXZq
            RktTUmpBRjdRcEFFWnRyYVRQTjE1aUkKFbFLn3HO7XZR3B3l6HctdpVuib5zNzzz
            XZnmsnXgXStyEt8RU2IR80wg/hBOLC+bCPGVEJpXA7VSNjSPpVvsaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T18:55:07Z"
    mac: ENC[AES256_GCM,data:SSFBzMpCnsdgTHTTvhbDYdU2+WWyvxfUYzNlwlPWD4Cqv6uF7T+deyPMkgsWIsSj28YS1tvWzMLkXUZH9Esq2ZnaFZj2D0470DcIKCY3YyaS7GJDTj23c9z77BFxM2yprYZQ5lR6JJeGqH6wsRzbUO792uWFLjucdr4OmuBEmCY=,iv:t5ClK5j4AfIoPiKyETdZqafePlHzOvfc+/yolH7QkEg=,tag:CUKl9HxH8hAtdJzy6O+2jg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
