ansible_become_pass: ENC[AES256_GCM,data:QIPZc6tdBZaO,iv:PQ6AGeaflYV0bHtRZMpZ4aQKO5dsJD9jc4ysRsxDgRw=,tag:PELAS8M5nZp9U8pMy2lRZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTzV5dE1SRU9wSEs4bHNP
            UkhSZjk0SytjUlNMaHpmZlhSRk5mbXhGblVrCnE0amhKNkhaTW40N1dUMVNHajhY
            WTFHRFRteDJpcUFiZnA2QmRTYXkzS3cKLS0tIDF4VzZxOXRsUmFqVEFYSHhoa2t3
            MEdMNVQvRU5rd2Q3bEFtS3FsTFJaTVEKc0heLDN5KePk5hS6fO4kz6GGqYTeT+2E
            0UmdVLn+CHFNi6gZdpKg48zk1xIG7rFmuxOMBJbweLGoH4NjorF9dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T18:55:07Z"
    mac: ENC[AES256_GCM,data:wGPAzRcBv2UVZcwIBA5TG98D7+b/wxQAKDGc/+XHwHa7GzMvDMZK1Qpzl6yU5MvqgekKqizKNwfLcRCcwz/pbX7jmn8Y7cxYy4e8YqTPomRz1OUXCJ2OtwwUVMGpO5Txxu18H6thnj5SWu5dCXroh1qm4dRnf6iWAm/wI3QjYDo=,iv:Hlr1za43MKsUmmRFiQMgD9HzOaVkahvaA1wxp1XVFPk=,tag:eGTqTzFn2X5Dk8ny1XBzkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
