ansible_become_pass: ENC[AES256_GCM,data:yQr6Klu39qE5,iv:zCgn77thLPnZEuvuf0Eug541gmBUbCu3H3mXIoByaPc=,tag:KVi7TGRUUCZa1k/h+ACiug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdlVoUHZDTlp2ekhERmpU
            azE0MXpzNEN2K25UNEVyQmpvUHlDSmh4eXpNCkVEUEIzd2dTTDBvNmZtVlpNZktL
            S3pqeEZodWVoV2dCZUhuWUs0bWU0Vk0KLS0tIDkwSXkzNkYrVXdFcGJiOGJaL3lx
            UkpBbURUK1haa1AzUXNZTVBVcUVRN2sKmAAEzMU29kaM92y4PxAWSAxCPh/TqR4b
            MyFOj60rGy41TQR/1XVLj5ewFdPca4NcA8iPI9xoJYbeQRJx9oB7mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T13:15:23Z"
    mac: ENC[AES256_GCM,data:EpgROGNCBvWWtRTn7YIPEcRWCe3x0GsWL5ZWO0mdDSiYxAn87mhJ0I8GnrlI+fejgBSwP4oyuVSpRoWrwSFRg2usvGUCVnOk7HFoxJ82FAdJxBG1+cq9RXe7JCMvLDmOiRFn7h1Teym5loS+NtzPZfxm0HbQ2JHFmKItIhLRnlg=,iv:MxF+HLchxfCtrrUmTLgEBCdowcuV4Qp1xgEdcrRQSvQ=,tag:36LKhI1N6mstfXpEJLtjkg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
