ansible_become_pass: ENC[AES256_GCM,data:DEIngpt6/b+n,iv:qguGnyLGMtXvW+mRqCrsRFHeKK5AxirMKjQIbCybk/o=,tag:gww2TOp06hoergGlbW+AOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdno1L0dCN2FXY2VGYXF4
            VWxxV2RFRENPaXBkdHFQeWdHMWZrcGpQdFQ4ClRyTXJIYWxRcUtXOTB1NXFQU1F2
            T2NydUprM20zTlMvWHFhUEJDbTJSbW8KLS0tIDRPVm9jeUR4TzhaZW5ZTWhqK080
            eUFaM29wQzhRc1NFekwzVDFlUVVuejgKgyQDgZzNqWN5j+6/fn1zFGaL7jisfyFZ
            UZjOLwA/PxzF0S90qIcOA1h+48uSr/SIFJ3Eu8wI6t7mryQ0a707ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-01T19:25:40Z"
    mac: ENC[AES256_GCM,data:66m7acPABQ/m9FJNtwFTfBBQbXBsYCqygXuRlHBEix7EfvOohluZZ2Elhr/TZJx1d3VINhGlOAvHb6gqbhcbDfLWt77AbohmR1MkVQ1rdloO5PskR0/C1YA10sfieD30l9s9fBbaIlNNCv3O4GkoEwLiK6tD8IeAaYbp6UjZK8k=,iv:ZgpR32QKq+uJYMRXvBSdtvvm+ugN2N3G/2qqs1ZUPhw=,tag:r+X/JKN38Tjmbo7G4DAFZQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
