ansible_become_pass: ENC[AES256_GCM,data:ODNfTaON9IEc,iv:xHHaf1gPNlN/BNzr2x9UI3c4Jpagr8EAWx/5GswJKAs=,tag:gXBvaFWHtI1hiuS6oVDaGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aUZaMmV6UllCbnEwNkxi
            V1IyL0tXRklzLzdZWDU0M01FL2RzYU81djNjClVPb1JGY1dhWTJxcXNRZ1JHcUI4
            ZVVjN1Q4SWZzTUxnUHJ5V01FR3lEU1UKLS0tIGtRczJYWTJ0bWR3Q3lmMVFkU043
            TkV3dm10eWFBV25tMi9rbU1xdFhaZHMKsIb8I5kC0MglWNpp19UrTJuw2wVd9YES
            qtsb7MWzbmo4o19oJPVk+je+fdVpqcrdW2em/HzaUNAAlxQCbAhX0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T13:15:24Z"
    mac: ENC[AES256_GCM,data:Cw1GQWL96FqsnDyst4leXy+AGvNosa2g5pPFoxpDrY+zKaAIXA1NzjI6ZCveat717yb+ocxIzfRUmI+imV6oDP8OHx4+zVB2pSXaKXKl4dr5KyLOZPWIPt4nRoz+OMuOJlq15mVA/bMqhs82OL3/dCcX8het/a6K86euuMiIy38=,iv:75scW1uCoS8w30T/THJnNQtc8uNXtz+3u+6mnwRzguY=,tag:SeJGlSvLlbGJpKXWDw1faA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
