---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8tz
spec:
  chart:
    spec:
      chart: k8tz
      version: 0.16.2
      interval: 60m
      sourceRef:
        kind: HelmRepository
        name: k8tz-charts
        namespace: flux-system
  interval: 60m
  values:
    namespace: k8s-tools

    replicaCount: 3

    timezone: ${TZ}
    cronJobTimeZone: true

    webhook:
      certManager:
        enabled: true
        issuerRef:
          name: k8tz-webhook-selfsign
          kind: Issuer

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: k8tz
              topologyKey: kubernetes.io/hostname

  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Namespace
            patch: |-
              $patch: delete
              apiVersion: v1
              kind: Namespace
              metadata:
                name: not-used
