---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: truecharts
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/truecharts/catalog
  timeout: 3m
