---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    env:
      TZ: ${TIMEZONE}
    hajimari:
      title: Apps
      lightTheme: paper
      darkTheme: tron
      alwaysTargetBlank: true
      showSearch: true
      showGreeting: true
      showAppGroups: false
      showAppStatus: false
      showBookmarkGroups: false
      showGlobalBookmarks: false
      showAppUrls: false
      defaultEnable: true
      searchProviders:
        - name: MySearch
          token: s
          icon: mdi:search-web
          searchUrl: https://search.${SECRET_DOMAIN}/search?q={query}
          url: https://search.${SECRET_DOMAIN}
      namespaceSelector:
        matchNames:
          - default
          - flux-system
          - monitoring
          - networking
          - rook-ceph
      customApps:
        - group: servers
          apps:
            - name: Unifi
              icon: mdi:router-network
              url: "https://unifi.${SECRET_DOMAIN}"
            - name: minio
              icon: mdi:aws
              url: "https://minio.${SECRET_DOMAIN}:9000"
      bookmarks:
        - group: Kubernetes
          bookmarks:
            - name: SpaceSyl/home-ops
              icon: mdi:github
              url: https://github.com/spacesyl/k3s
              targetBlank: false
            - name: SpaceSyl/containers
              icon: ''
              url: https://github.com/spacesyl/container-freeradius
              targetBlank: false
            - name: k8s-at-home-search
              icon: ''
              url: https://whazor.github.io/k8s-at-home-search/
              targetBlank: false
    ingress:
      app:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
          hajimari.io/icon: "weather-sunset"
          hajimari.io/instance: "admin"
        hosts:
          - host: &host start.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
