---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.yaml
configMapGenerator:
  - name: blocky-datasource-tpl
    files:
      - ./datasource.yaml
generatorOptions:
  disableNameSuffixHash: true
