apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:IY/qWdvjMQqmZeZ60JvX5VtQfUZWoFzPHd7lOxkGlL5UK6ep,iv:QTAD6D+f2TsdOXZZRHhCKnXJWT9N82ILXrpipTVs72Y=,tag:5DAwb7Oe0hS7ZxkLhSSroA==,type:str]
    credentials.json: ENC[AES256_GCM,data:fWd/JGltxHcER8GhXP0WD31g1SXRQ/aIRFscG4DnXv51MS0CyRTByQAbC9/NazyTGcasefrcUbAB4z4VSF03G8gvihpx4yNk3INmfK3v82b+RcydNU74vaWfyUV4gK6RvWdmnEqNgcLY7Nsxo/8LZhDE2AoUjAHrMhBQHEL25dDF9eiS+xoaPP0tY9anpYvU4rgBwTRMa3zKOLc4IVySTYsQdRpN5X89Uo4Fs7N6Ig==,iv:rqF1SGZcfzSmwF0NgOfyxS/SWEVd66ufPC2ijZuJp2I=,tag:Gnmgna8+UB5thE8hK5yZsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcHloVlN0K0JaaVR3Nkho
            QXA0UkI4RWphT1FQcER2azFyNjVwYXJsOW5FCjlkUXhSK2dTNHVDWTBTU0toTS9T
            czVJbDNvcWg4UmhFa2NZL1Iyc241bkkKLS0tIEN4dEJKZVMzR2hDRUs4cmFKUFN6
            T1JodjBuMC80QUFBaE5rdVJmM1dVS2sKW2ftRdMheNDGizaqyPu0lTRdugfY6ah+
            lI9Ja2il7vkda8PqQvY7z45t3WSXnXPgOOJRvIAOOha9f+2gtnFOZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-04T18:55:56Z"
    mac: ENC[AES256_GCM,data:/w0FvkZZoRB8VX92p1UgCujeqQpd4qD17dUXRuHEvGmJk9x9VtVozDvjAB3rhqOGupBTzJ6jjg7KLv0rNaCJD3Nr6HCpeuDCK/Alj+GX94fppdNHcEpeBdZ9m2Ie67KjI0QTLJGSWUMWLbP3N1MqksQRFcOpXoUOgSs45FuuPsg=,iv:KkWSODukoYXihzSeVhlqIrk3dUtFvzzPRNKirVdI/fA=,tag:A28ryjpyWPHv/hdFVUwiuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
