apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeWxiM2RLcVltWklJWTVP
            Rzh6K2g4cnhXWC9jMTI2Zkc2UkFHbDJjOXpvCkZjNTVOM2JkTnV3V05KbFN1Z3g1
            ZUpJaCtXeVNrSXl5UElLdCt5ZUIwV0kKLS0tIHVmdGVkaVlZbnlUK2Rzd0JEOTBt
            YmVpTmp0TlJCR1M5ZnRhUVZRV0RuUXMKIJl5mKfAXELbVMBnwmkXxYbf/1LkQi2z
            oOZ+2nRgHEylX5Zr+N5UoG6KJ3l+sJxL31kh3t+MFUksWW8Sz6YDbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T16:18:15Z"
    mac: ENC[AES256_GCM,data:t8sTNuTfZZ/PbjT5H66DNa7kTcBPSjWrER1YnyNDm961nFTFnjcWNCYC6SbNbvxETixVqaAm9tdJz2pXbBx6q2MtZv1jEOMZXzOqJ1y51L2cB43DW4ScUkzEZLZkuCNHAVOhs2njhrVeXyFGkEOLuLu7EE4i/ZqIyKzzLM11MAo=,iv:VU5P2cGS/uJAP9XEVTcqe8e0AjCx5Ddz4oeO/Mvt9Lw=,tag:B4zJkV5NP3CoCHAs6TKV5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
