apiVersion: v1
kind: Secret
metadata:
    name: pgadmin
    namespace: databases
    annotations:
        reloader.stakater.com/match: "true"
stringData:
    email: ENC[AES256_GCM,data:dLwn3B/SLizMX16KtUaYYiXQfWWNxwPn/aB/5Xef,iv:hj/DOzr8lXmDKtnk+cV/5Hj5evQWrmLypuj5Ayft+Uo=,tag:EJljXgYPun+QxFsCbMbHWA==,type:str]
    password: ENC[AES256_GCM,data:9cNz26/0AzWXtL56PQtuUvjOpEIQmwT/JgyiSdXLg1ISyN8ZfY2wZALt//G3VXK6iWt9/4C9,iv:ukO+DrPOwd0oOdI0cCBVXoTN2B5JHlRpXeiH1hao9Bc=,tag:5VsrWI4JnMo/jW3sks1L9A==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:VnPMSFS3QcjgUUneTEvKipTBfudx+D7o893aAeW6WF52HoQ2uIA3RXg=,iv:xClcH7cWCbaE0sCU5OLabNVqiH2xSK9Bfft2ygYFA1A=,tag:wIH8iGPwjXqwjqZ7wgSaCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeUpVUWZEbHVTYnhBaCtG
            alBxYmZuajlEQ2lOTU9DVU5RVHk4YjNXQ0NJCklyMzJXTWVhaVJENUYrVFV3L2pn
            UGw0M2tVa00yaDBEdzdNZFNqajU5TUEKLS0tIDlublFyMGU5ckRXV3k1Vkk1bGpr
            Y3Vlc2J4NG53K1RnNWtXbEJUa25aenMKMXo2o19IisPDZJOC5w3QaiGarYCsh2T/
            rink3Z4GBJA2nYB8PNTo5e/DWeSQ+bxSRPBgKdXofft/2oRTMKXclA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-04T22:19:34Z"
    mac: ENC[AES256_GCM,data:uVyi5cvwsEkCqadzc1Y4CGC7ZJALRpw9Na6GJlUmbADWZodx82gDsF+rfjWO3aX+9vcJ+yXVN6EeZqG/cTdtHi3ZDGRx7hchdtH6/ijJbkzaDXnA1SIo3tLXiauz7q2seuOK/lgkCcKYekfP1Y0OySdR6o+1v+SzBO7UkxlPLiA=,iv:HNaC+Wn1d7nA2ojV878LpAhbki+L3Q/qkCfmSYcwqvQ=,tag:URYBAZHCAXpdkFmhPzcg9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
