apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-es
  namespace: &namespace databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        email: "{{ .PGADMIN_ADMIN_USER }}@{{ .GLOBAL_SECRET_PUBLIC_DOMAIN }}"
        password: "{{ .PGADMIN_ADMIN_PASS }}"
  dataFrom:
    - find:
        path: PGADMIN_
    - find:
        path: GLOBAL_
