{
	"data": "ENC[AES256_GCM,data:rVACjhUYKKuw95h+7PbhYdUpKz3TeF4FUhBzkyGUiCrAF66iBBo0kEwO2EaL4uF9mOvSc3xFxRFVJ/hatb+94u3TtddFZ/TdrSgSXNYpG2GQbRgpZ3e5uiKrd0LC6fHrf8j9mRV14obnwiVgAuJ5E1ttYbx27yiyf2mkkptvfvW7Ib8bAdqgN37laNNPL1wFcU8G+6jfzodNza8+7nBHMsq5g4dLDyDEU3mVKiwGsihR/3MHePQ1CzCnbcVoNfvw0fhyMewmm4KIVeCvVXqwDC9aIZQfYfQpteCS6KSoEOev2bwbQlvStcdBM8akN2JX5UoAcO8ppYs=,iv:EuDPtlbRQ+JFrAYnXtPPv2zzvfbu9c3FnAMQXMltp+o=,tag:HOe3pn27eOJJaMv1F6xAaA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd2lzYzZMeFdWUGFVam9L\nMWxabkt0L096MExVaVcrUnJLNU5zY3h6UUVNCjFJL3czU09MMkFINVlVeitodFJ3\nYzVxRzM3WDZEYkNYTC9vZXJtQ2dmN2sKLS0tIGNWcytOb1VEVktpT2pLOENPYVh2\nZkJGamlQZ3NEOUJYaEd1RlNTNFZqYTQKFVySON44FVQG0Bj437i5nZ7PFXDUJPSm\nskqGTf2pEFG/yXv3Uzrytma3qTeTz+r+lRcqgMaY9Fvjuq/pfvaj9A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-01-04T18:34:05Z",
		"mac": "ENC[AES256_GCM,data:+0xw1eI6jeMLBR8dq7Bo7TRIyW3LmMzS7HNvYgns/zHJ1l8jt8SDoQN4+mRSwUGLp8tvzvveOhUrxxILPvvv115xWomEWPSdGhLr2VlI945PxsM/Pm9LMObMs9+ocNvp52GARJJEigl5RDctiz1sDP05/W4Fs39EPEfg3M0MHOU=,iv:nn3PcT7Art2IPjyIkpBUdNvEhotpghTF+SAkybvKWZ8=,tag:JhMagDXvggpdl6/ryCbafA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}