{
	"data": "ENC[AES256_GCM,data:YmEZnYiS/PMitfl0ZlkSqaijb9ZkyeWPVMlHcU4DiybS5KktbU9KNCEkD4sVZUaG8UdEvK612DrBP+/vzpumGeVFZ9yxJFBFmWI8ffORi42OQ4EN1j+k4iHymxTnO/nKakwQ4Fr29+8GXOMKTqxFnoj3SFBnXsz1Ac8LWmzB70mYSqxuE0gXqhfd+G0aKSWv1BVWDpqYZcPzZA8WiU22oyAN84Z2L2Rz2vuf56/rmrCgIG/oNxqPY4aB8dnRWNMMGzY/DGg=,iv:b7jEFm2XWlg4Sf1ESog062j3jVNSazCI0CufhEmog7Q=,tag:x4OjBY8r+Dhmpp75ncUlAw==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd2lzYzZMeFdWUGFVam9L\nMWxabkt0L096MExVaVcrUnJLNU5zY3h6UUVNCjFJL3czU09MMkFINVlVeitodFJ3\nYzVxRzM3WDZEYkNYTC9vZXJtQ2dmN2sKLS0tIGNWcytOb1VEVktpT2pLOENPYVh2\nZkJGamlQZ3NEOUJYaEd1RlNTNFZqYTQKFVySON44FVQG0Bj437i5nZ7PFXDUJPSm\nskqGTf2pEFG/yXv3Uzrytma3qTeTz+r+lRcqgMaY9Fvjuq/pfvaj9A==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-12-29T17:35:00Z",
		"mac": "ENC[AES256_GCM,data:CwRcSWqtaQpYtXyNpUIdIn5fiSwZ/1PvtPOJMu/aT5RGCR0BIYKoLB5CFOs48SQGkcahPA/3mIzrOqnxQjHOxEdvdArXJ78fN+9v8LktmOipqkPk96bLovU+pFh/rIoUs6Uj2WHolzTX20LbMY7uD+cuvQJSc1tJi1PS1LcWknU=,iv:WC4G0Z43pwasLmAWRyrmbXl4V91JaBQPmk7zO5pa1vY=,tag:JundPxlTIEcybF82dMegFQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}