{
	"data": "ENC[AES256_GCM,data:UMS81grofOA4sQRsZX4njNQY8wz459GYYCd2RNr2LRSwMYiQgJq1nA9Ra0hte1kVtyh/lTLgbYjUU44UAXcNV/ho3KdE0Pt8dYvShratyP+3ToeiO4YAdDuDBVfmw8CaQfUqqd4JuEwV22U5E7eYIeIuVgC/My5R0WXEHDxn+fK7zzPqC/CtYC6N1BbCqWtpijMCLgDNkP/o6i5C+xP/2KOv2656uUvs9Nq4xylpcRugiErL3f+rcVDC+7+ZkCD6mIh2ImqECi9rGbkRk9K1V+vqqbNVYVSx5seE+FX/GoHQV9cqcE8ZUL8Nhyl5qTWNLjgL40OhIgG59H/QmaulOtvFczkBeDLAvEMuDIWngni31NoOa3eSVhN60ejIVAYe4/PPmOVQUhRwKaxpWyelpx1Gbl8Fe1aEKUHXVagn9XdA8PmIrsiKAg066qt+9baoxJOfELxVUl4Z1N3VeyIn8ECVtfAA4PnQDxzZQfhvuZgQZKhEF3PTz4d/Ehp838o27251qpQ11gSzak+mc/3i0oJU5nG/,iv:IimW+vX4M3He0ZImOSo/BRreuFyW0XQEVaK2fVIB6yI=,tag:fRpzxOG0BxHP/je87QPiaA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleVRxZjZGcFVFR05QcjZU\nWlpWanQ1WE9MdHNja016L0NGRDNCaWhJTEZZCjVGcDBwNGhGY2RVUDVGMEs4d2Rp\nUWxUczkvS1Z0ZStSUEhkZnBRZ3ovelkKLS0tIHVySTY3d1RLWFV6d0RSQlpsZ05M\nT2dKeVRtNlJ5bnowanByZU5Lb3JHWkkKUgUgzrtodoJNiO4ub/kMDD2Asy5tJNhw\ndvUyf3RpXn9zbCWw+OkW//7XtRzbarP7K1KDJuObaO0f7VtmrT5uCg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-01-03T15:09:56Z",
		"mac": "ENC[AES256_GCM,data:XlMKvfEd7wbRG0Ct1+I3NApbzEjcEJc/8k5AgEWI+zrCegXHHwDTJo+BdNwoEHo9poZZ2Ya6ndO7LzCu7zY76jg5VQIoTFKZS8IkN3AnoXwz3gDlDGBBdO+O5nnqs+GgfegmqdFaKt0JwK6EJurq0jg+3Q6XPz7JyT9/2mPWtrA=,iv:MtF7omOQLUB3mHL2mJba7aPlFHEQxCgV+tzoRKQl0Uw=,tag:uEoyMqAwkxE75kWi2MQIZA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}