{
	"data": "ENC[AES256_GCM,data:OmckqTq0Fsg7j7v6J/Dyqh0uZcfP6dtJet6xTE8htXh/tVSwNCLSIjdTTCG+sQvMMxxXszRTqm6IiUVWTlBH5Aiin+fp7/MvGgxpLjKV3E8kd5DREz5GOtHJRSfqsthVmpheNGIzHujvKR8GdP/n3dp1j9lik71cupBVObnoojatPDvHix/iujJLjYXTgcV5puKQS1zaYviZSqAKcImqmerFTLkUv9Zz03HMSIjNjaF/L6CiUpiB5BC9Jho/yoxruP3Y+6/4P/gWHvNnRLsryJ76j+q9Df9DRoGd2BgnLmeEmatoRLmQ1icmVwbQPZ/v6fwQgSfoze9muVkRR6KndVZMRPAvACAHAHU/BJ19Qp6c2IczqS6PvrCRLIbYZoGrzlshvhxKiIUODtHbCobYCqNXBBXQS4yG/GLP4e2UZcGN,iv:09x9ceEyi9yZB5lCXzeaLf+3+05/jjCbDzOEhNmnr+Y=,tag:toNtPenQmQZeAXiskL/paQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleVRxZjZGcFVFR05QcjZU\nWlpWanQ1WE9MdHNja016L0NGRDNCaWhJTEZZCjVGcDBwNGhGY2RVUDVGMEs4d2Rp\nUWxUczkvS1Z0ZStSUEhkZnBRZ3ovelkKLS0tIHVySTY3d1RLWFV6d0RSQlpsZ05M\nT2dKeVRtNlJ5bnowanByZU5Lb3JHWkkKUgUgzrtodoJNiO4ub/kMDD2Asy5tJNhw\ndvUyf3RpXn9zbCWw+OkW//7XtRzbarP7K1KDJuObaO0f7VtmrT5uCg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-11-24T15:17:19Z",
		"mac": "ENC[AES256_GCM,data:wcGt79p1Qk+O3k2pK7R9K+Fqp3SLh4/OSMm4SEC7hg/rzOZnX9LRmCuZ9jMceLpsqNWp9/ltILE/YPqLoxemJUDw5ZZYSR9qHA/JUXYmU5mx8dLIpzMlLe94Crum5KZHO80URGQ3filap7y9/ZW13MqpgnEW8yIC85fGRig+zrc=,iv:8iHrnn2vtf3z4hWWjIptW6fckDBEFFWQeHdV4/0INLI=,tag:axKGVj1YK1XRF4kBMiZyeQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}