{
	"data": "ENC[AES256_GCM,data:3tJV/G5IFOwRvsdwGw8gMsjo+3xohwUSmwlz56JGr9ReJAjrJJArb+FILLtlO7vGjBQP8YqzJNkezlwd0wFXD1HO4UMWk4PPTpWzTDltyVcDHwga0K9utpEluoK9WSXWHMjtKkI7rzqLpysqOWCSqwpaO7bxqKfK4QKOZX0L3zHJS6WfQT8G219yrp+NR9a2snRbgNalvXIJPuaRSr935KaoaKLx+4dpzunqrhQZvYCkEZDivccdl4C8fAq0OasGtYTlPFEY2ufHXZtanYoJmc0NmoV2yGadSCGrCdYbyEaoCPkXglW4gwsT5RXbZVPIHwMRg26MbVEaVe1RPwGLPTAaMo8tUkIDeIUWDkFc8Mmoo0zy9w3M2L4P2B2YCbr6T83gF0F2peVVuOZjkivm+Ck0vMSgtwor1st6epZuBa6oGiIwNxJWdjc23RgpSFw3m2R4,iv:+TOkjpBJ9FKAoUa4/xdYxCh9grMQYeAal8jvvahuVsE=,tag:F9d5ApuBbKMcgfsWd9tmTg==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleVRxZjZGcFVFR05QcjZU\nWlpWanQ1WE9MdHNja016L0NGRDNCaWhJTEZZCjVGcDBwNGhGY2RVUDVGMEs4d2Rp\nUWxUczkvS1Z0ZStSUEhkZnBRZ3ovelkKLS0tIHVySTY3d1RLWFV6d0RSQlpsZ05M\nT2dKeVRtNlJ5bnowanByZU5Lb3JHWkkKUgUgzrtodoJNiO4ub/kMDD2Asy5tJNhw\ndvUyf3RpXn9zbCWw+OkW//7XtRzbarP7K1KDJuObaO0f7VtmrT5uCg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-12-30T17:49:05Z",
		"mac": "ENC[AES256_GCM,data:Pup7E1vmbJhLTHohQxoGuDjmNTCnjXhNAufn+zIMSVK2c2n56dbwyiJri43hFRwzAHic5uMYmsUEnbx+rUSZa/bjOW5uVPmaw8JPZW1UDRvkbuoUykHi3RNRQ28w8LQM7bZomaua0kTcmTsv4yYpOKiJpa6K2v1IMOAamOYToZM=,iv:N3+7vnUPI0E5XdE4DHDnhk1DuS5y8T+o0spdSFnRjeE=,tag:mEBoYUZiL75+FO99iSs/Lw==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}