{
	"data": "ENC[AES256_GCM,data:R0nIqJ+dfaM0xUKORVZuJIeoA/ZlEtB3Ttu22NEkeoJ83inM5VnjPREml7zz3hVANVohMLNlY4mpJXNrUX7tR7lAU9QxLmTDVJE0nGQyP1wZLw4bDReR8PgLGVxf8qzK2WnscpV8VRLf8rCPFBPL+dM8j23P5B0UIX3Hn8hNeW5GRFFCSXeeeO92rSF+1pICvnN5pgz7gSO/bwU00ff8Uv5nPsr6zXKWISgA+FpNbnywymhg9tW61PuorRR1OseQCDiz8gypkan75mxzldOQpt219TEiQZiy7NQoDGB78FfEbqSz+AtqxL0+YOP6hHEhLN12aqmZjRkhcyra7VRIjS2tT1jRJxFQC3eOe18kjZd7IgThzUrPZ+z1ozCssKri73zjsW+nsdV4guJY6vuoKl4g0QDckZuZbzomYovuvje159X+0/se5gKLsQbO8Rf5b/Ki1gSXEIGrAl2xCIybi2xj+JGbDNw/3IaoREiLmhXjTWOvQWrC/G9v6AtGbhv6QZ+qTMP9ts0yKlEjLeRosOXeEjiFMfCbVUJjv23FKty1v5FapRpxRQ/qkacslqYtiHC3qPCxb0urIENDB1gHeZy3oS4JIggcheTxf3VMFtD/CrHHeL2gaIBGW4EyYNKrA9HJBXwxha1iHjBDvTX2Lu3oC+Mve+kKegP7xoQuRoDV5r/FgcQjtP3+onED9FrjpSgIrtT77F9F1LLh0FaL8hLgMFoOPwrx54bqOjKyu+2ICY/HLbe4OkRbcbzVA667nJ7BC3PtQIMeMxcULW0GMgV4kpeBmsIvfkV5S/H/0gv+fz2YgCBsUFMefd331Xd46D5L3P5RKMCEBwRtgOy8MK//US9eILXQPjzlHBeyAq2bEACsUuG5vomOhPN8yKPbrpVWSQHUmD4o8k6RCLK4/Yak8E8TdogkcsbHT98nTiI49+ZEehKv6dNP3ANcJ29BDFGojxNfled9HPd3uScTdg35zfQJKezG5ComhtCNFvAAn5gFAiBhyFxK3gNbLnmimLNY/jWOf/T01cCFnYE7ldBqYBVsVsleqLnnsGKuIQr4PAI3yyfJygBZvtuD9hYSYoacLj7mjFIrQv88cpE/Up3fzwIVwY3RWCXPre5AQ8HuXJ+uiQnS861obvqXVtEp3urn2I3ATu7hjoxStbBOaMZN9DpQ8ocQyVl8FXaMLeCjRXvU+ICTda2IQ2eAtzUsSvK8,iv:/8/KEDwoqnsoexE+k52Kc3EmOVGibhQVm1E1vbIa7g0=,tag:XlY1m9sa/panlZ9aCxoAiQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTS9QM3JmMEhMekdwUzIz\nL1V5NDlXelpROHB5YzUrem5sWU5DVm1yVzBBCmNQWkpjSjc5WENOOTNsMm1sWXZJ\na2ZWN2ZHRFlIMGNXNTFXNjZzek9tN1UKLS0tIEFpQThZZHVTRndkMG5GQUdSWmlz\nK2tSMlpIUWRwMWsvOHF6VnlxWkxvVUEKV5bxiDOFphUT/S8idd0YDC+yVcWwSYgk\nGihvpxHGDIfKd/Ms6FxjhELX3gY8xiYSVGcvQN+++WvVanmxy5Vf5Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-12-28T18:49:38Z",
		"mac": "ENC[AES256_GCM,data:VVamTkCzDXrn2WdD+9x53aU3q7bvKt9AtuYMfIiEmeT/nJbtIF3FKtCRgZPTyaBov1143v7ko1IVbDOYP0MMAYxFcfPwctfGJkZXlgZmBw1JZZQVr1VgO6PXs6pYkbdBpedjAbGWBTTcC5O+NEQ+pfwmrbexE+q1S+z/OivgBPs=,iv:npVAH6CbNf1AzU1xO5Rkx0xKpRJzoY1POe7/dlDVBHc=,tag:b+bYvSfa4te599ScsQJmtA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}