{
	"data": "ENC[AES256_GCM,data:Li1JLIIyjOHD7AaACR9VdFKuO8ZV4hSSbXZY6gkqsjsIBM0yANpfUEf7OjA50EB38ht6K3tzToB19ljOV7AfJqciKBfB4Q8eka0mR+2eW2Pm9oBuZ4Vx3SEejoLLKmsDZB+tX3i6ENq6dGHKVBUWIx2VXVm1lZsTK2ZzK9+H6Xcx4AxdPguwidrXHruEjFMbtvXGFFSyDQxgd0Ivj/DaV1zCK9Tm1DG7IbSJVRmJNgNABn/0vLokec6bkId9wQYPzQzKp2yuOW4MSwokHqZEBFWQuHdBj+EOQyU=,iv:xO2LkWbLB3//DP56WIsgziPJxMAOLNiOELfYUtAS3j0=,tag:o3HDAoes5MZuwU8izhWzkQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTS9QM3JmMEhMekdwUzIz\nL1V5NDlXelpROHB5YzUrem5sWU5DVm1yVzBBCmNQWkpjSjc5WENOOTNsMm1sWXZJ\na2ZWN2ZHRFlIMGNXNTFXNjZzek9tN1UKLS0tIEFpQThZZHVTRndkMG5GQUdSWmlz\nK2tSMlpIUWRwMWsvOHF6VnlxWkxvVUEKV5bxiDOFphUT/S8idd0YDC+yVcWwSYgk\nGihvpxHGDIfKd/Ms6FxjhELX3gY8xiYSVGcvQN+++WvVanmxy5Vf5Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2023-12-28T18:29:27Z",
		"mac": "ENC[AES256_GCM,data:4waFo/UDXIk79RVGXvN/u2W6pnv5WjHhcnTiX42FAv7pOzYkoYlDKM3Vt+gvlQuDabC0Md2xRUH+L8a/CmInCrF+VkQN4+14S7y0syKHDRTGaV6VImAh/B+loX7qoyx1Cnq3Dm/ZAEDRXmBmci5Z5CRuHw3ji/iPMnGV5iEQ3Uo=,iv:vyFqDmQdPRRPcEln1Ggx+3CrWAo244XboiI9q2Lsl4A=,tag:Oj2YbWmastEUAWr1cXGteA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}