---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: storage
spec:
  interval: 12h
  maxHistory: 3
  chart:
    spec:
      chart: operator
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
    replace: true
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    operator:
      replicaCount: 1
    console:
      ingress:
        enabled: true
        ingressClassName: internal
        host: minio.${SECRET_DOMAIN}
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - minio.${SECRET_DOMAIN}-tls
