apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-authentik-es
  namespace: &namespace databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: pg-authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_AUTHENTIK_USER }}"
        password: "{{ .POSTGRES_AUTHENTIK_PASS }}"
  dataFrom:
    - find:
        path: POSTGRES_AUTHENTIK_
