apiVersion: v1
kind: Service
metadata:
  name: chrony-udp
  namespace: services
  labels:
    app: chrony
  annotations:
    io.cilium/lb-ipam-ips: "10.17.8.5"
spec:
  ports:
    - name: ntp-udp
      port: 123
      protocol: UDP
      targetPort: 123
  selector:
    app: chrony
    tier: frontend
  type: LoadBalancer
