# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: earnapp-secrets
    namespace: earn
stringData:
    earnappUuid1: ENC[AES256_GCM,data:bYNMNfCqvE5peqIUzpj3ZYlBTdLL+kgEvBLW/MlXVAi17sLWJm09ihg=,iv:IoUFD8ce9cWga03imrlEiW4BaeYL3LiGY/1ZWuEINx0=,tag:ZGHKEUk1jXsWWL3imHuhMg==,type:str]
    earnappUuid2: ENC[AES256_GCM,data:N+hQUTHsv0cG/qb4QQaGdAjZ+o+QU02mIsjhA/4rfvo5ub7RoYvo92w=,iv:20eEmbzJ5fpICxDNMe3MFy8N9BqYjsqCIVI0UpNeFak=,tag:dEs+fJzlhG3Nj26ND0GsRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVzBlWnorVlJUT2UxdGw1
            VkFmWmkxRVZwUEFvbkpnR3JyMGwxc2JoajJnCi82OTN1ZzlQeUZtM2kyelZoa3hk
            OSt5ZVNMbmFDUHdyc0NYQVRXWThzUzAKLS0tIDVhakcvRnpNQUxlODJ1T2p4bURv
            UEpYMHF5TDBTV1FXQzZLcGZxVEllaGcK6R1QSPz1ouYOF0uiJFEtMXrUKJPMV4Jl
            bCPHeeoZynNfEyq7vodfDKAXrxJ1BC/I4k76TqzhBltWv0OdPc256w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-09T19:03:29Z"
    mac: ENC[AES256_GCM,data:g3PotXinfA0OKYbKjT4tCSbsQlNChyOU5fkoY4iLFUIKT5GWN9kPp1AWT8gkub2nYLT7b9vkH6W+C34EqfQ5kZl0joYTaT2smVHJKAdgHbTNhyaBnjYKuJaBpr6xgT9yvv60vFlP1qkzezWSoVOYoOgxg/JRZiRLrrfRA8e5GW4=,iv:dTfjMRuf7CDVnDCjH/qOCZ9w3yqsa7L0c1ondInixJM=,tag:nOx/+LIMnJIBa9cco9WfbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
