---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: security
resources:
  - secrets.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: authelia-configmap
    files:
      - config/configuration.yaml
generatorOptions:
  disableNameSuffixHash: true
