---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: security
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: authelia-secret
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        AUTHELIA_JWT_SECRET: "{{ .AUTHELIA_JWT_SECRET }}"
        AUTHELIA_WEBAUTHN_DISPLAY_NAME: "{{ .AUTHELIA_WEBAUTHN_DISPLAY_NAME }}"
        AUTHELIA_SESSION_SECRET: "{{ .AUTHELIA_SESSION_SECRET }}"
        AUTHELIA_STORAGE_ENCRYPTION_KEY: "{{ .AUTHELIA_STORAGE_ENCRYPTION_KEY }}"
        AUTHELIA_STORAGE_POSTGRES_HOST: &dbhost cnpg-authelia-rw.databases.svc.cluster.local
        AUTHELIA_STORAGE_POSTGRES_DATABASE: &dbname "authelia"
        AUTHELIA_STORAGE_POSTGRES_USERNAME: &dbuser "{{ .POSTGRES_AUTHELIA_USER }}"
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: &dbpass "{{ .POSTGRES_AUTHELIA_PASS }}"
        # AUTHELIA_NOTIFIER_SMTP_HOST: "{{ .EMAIL_SMTP_HOST }}"
        # AUTHELIA_NOTIFIER_SMTP_PORT: "{{ .EMAIL_SMTP_PORT }}"
        # AUTHELIA_NOTIFIER_SMTP_SENDER: "{{ .AUTHELIA_NOTIFIER_SMTP_SENDER }}"
        # AUTHELIA_NOTIFIER_SMTP_USERNAME: "{{ .AUTHELIA_NOTIFIER_SMTP_USERNAME }}"
        # AUTHELIA_NOTIFIER_SMTP_PASSWORD: "{{ .AUTHELIA_NOTIFIER_SMTP_PASSWORD }}"
        # AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS: "{{ .ADMIN_EMAIL }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET }}"
        AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY: "{{ .AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER: "{{ .AUTHELIA_LDAP_USER }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD: "{{ .AUTHELIA_LDAP_PASS }}"
        AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: "{{ .LDAP_BASE_DN }}"
        # OIDC Apps
        # GRAFANA_OAUTH_CLIENT_SECRET: "{{ .GRAFANA_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - find:
        path: POSTGRES_AUTHELIA_
    - find:
        path: POSTGRES_SUPER_
    - find:
        path: AUTHELIA_
