# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nM/35bLFBgCjO6++su2IyVBPXNgc3xbxErkPv0JsVvQ=,iv:C00E540Aaj4xdWRI/ZXOjbYfebtpbhEcU6mPTis86Vc=,tag:vIic1luEsJp2Y507uY7DrA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeU11bUZjTldTTTFFdEJh
        M0hybnFRcFgzWmwrYWdnaU0yOXFPWnZZbXpVCnlGdHVTOTRLUkM4dXBNK2loTHhp
        S3NmTUFuTkpqMmZEcDBkd2FhS2JTU1EKLS0tIC8vY3lIZ0owYzV1dWhTREVLb0Jn
        Qi9VM3VuY2l1VEhXdVBDa0ZiYXlHRVUKz6R5K+GOXHBACsWRXOp9baF7hKsLFkh+
        0DzEqihlaYDxS8kTx+C/FdxtT+nL/mQJ53/bTJ92b9k6psY5WuXqmA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T22:41:37Z"
  mac: ENC[AES256_GCM,data:2jsXLGFTDNxiiY7DQ940amNn+Um812ARs4Xmf+UnlcgZe0VYx3Wd7lutabQult4R/KzGpjYj/hVsFyRMIVzXlL5FrXcIUr1c/OmEk63IDhdI989dSsZf//11ii+7h/qIc1Hrb5OAvlNDL9hrgmC84eKhKj3XoWnEoVU6Lab+T+k=,iv:u043c4XQJWGlR0lRNreBil7pn7gfcfsOkflq4CbWyIY=,tag:+Z1CdyazwDp2iSsolW+yXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
