# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Gs4ZSDJ2Y4IGmzy/we2JtuldHeSWlhhKXHJxJNf3z5E=,iv:nOstesTf1aJhvjsJg9jn24ugdCNUxjYYtM+ixOrURsU=,tag:ScEowygZyWKuQVN/rDstpg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U1dJR05UclR2b3QxTHhY
        d1hKKytpdk05d1ZWVU5HMllDbVB5STc3ZkZjCmFLek5wT2t3Tjh1OXlQYW8xK2lv
        VGlxNVY4L0NsUjVFZG1iMjd2QjNMWFEKLS0tIFdvUlZVcWNmZnZHVmxXSFdLUmRZ
        cnRGNVZQN1cwYTNYclJOa2ZSK3dZU0EK5l9vm1dSTs/VXZn2ODy2XzitDNNa2gIs
        Sgsqsw3cF08LmUDZnwPD1w13f7mk5MPFqvtRDnoLx5e0vvRMYv60og==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T18:37:07Z"
  mac: ENC[AES256_GCM,data:YTZ5rkeaDRNiB1q3oq0rMAxzPPXEPnsDzItAFEifjbd8jQXntnUX/yo/OV1l6YFdBC9hQlAv+CtNIwYMGlOLUKQvdpGwG2Sp7u280HyWYwayXBvwNEu/pKFfCA8X90kzGL8nAC5e3S/spYdfdopLx2veRxyqcToTfSDbQuzQNNc=,iv:BmAKGTnMxL6LZ83G6qJav5A/4AR7/hKZKOv5U4bFvUg=,tag:lPlfFZaanAqVWheah2QjfA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
