# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:NgQVr3h9OOjjWGW5wxQNQ3pb61qeQsRyhYoAMhGyPKA=,iv:KDWPFBxFeLhcvV+FSWeWqYPMkJFcexPkr5cO+/oXvx0=,tag:p+vTNtwQcJNxOTlmDjHupQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VmFWNEh2L3Jib1pKWGQx
        aUY5Q1FPRkNuZ2VnencwV1hLVkp5QWIyZ2g4CnI5L3N1ck5jZlV1TUlkRjN0amZ3
        Zi9VYjhqcFdyTmczZ2lmbkNlMGVhL28KLS0tIG5YOEhHV3RRclNJaTkvWHRsOGcy
        OEFnWEJSV0RyMlptWkd3Ky9uOUg0K0UKRPEgjpyU0wGVj+3ExtALoduqYknZdOPP
        55+meWr6DS1+bEiflOK7UzuLDqea69opRrqnIrlEOqFgJ8SIJfkO7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T17:10:51Z"
  mac: ENC[AES256_GCM,data:7RRkG/83vl7aowxZFa0DArbvE+DRrfFVEdLQaFmt+lNlI5t/HnD3/i42x7IqupKJ7eqVlEjx9+hf7KjSQ5rkfoxmdy4ZaThHy1EBnuWSrlo/2kyQPP7edcI38ft7UgZ3tKSWWXKgvEML9W2WG2x7hEXFdpr+Y+mNAlb4IH+8fx4=,iv:8yJ4gtj9GeOm8AUIPQ+ITJJgXi0tP6/3QM8z4fLpGlE=,tag:uGf9EssF65KomeD8wfcpyg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
