# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:KMJuBm5NIf/vKITiHer9ctTDglOoaLJ7PnyET5NL5vo=,iv:LGDrYc2DoIdMuBga3NsUmxlJ0mmIBKKiq/gqmCScpY8=,tag:Dnz7fnP8RE4MSsy33e07qA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZG9vblhDVHVtSUg3MUdo
        RXlXS1Bzdm81Si96VFk4bFhLNTZCWnNtbEF3Cm1aR3luREovWmZMNXRsbnI5Nmly
        VDhlZHVrcjR1a3dYYnR4ZkNrZWxYWm8KLS0tIFNqQll4MGhCVHdBL1JDV2QwUXAx
        MUQ1R0Roalk1L2pJeTViUVAxNU5uN1kKbaZGvEBsgBUI8M8sJ90YnMkSzWeOXWel
        etqbHn6wczXpPYBsHqyJGdzqSI/Aa0OvBq/u7FAKBODDTgYdYe6k9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T15:20:58Z"
  mac: ENC[AES256_GCM,data:aah5+n8Lq+OmsCTLR9EtdsFCFH6UfOhF4ur3lr57KcjUNbL6aRaIRoEBJlCKj04nYNz4zR6Ru5f2YRRKEkdt8ofK9Rl7FkP1HDACpfuC0uIk3J2WVomGwNZKsUdjjAKyC3lRHJ6r8Z58Qj3raxKenet4aY9Yuhb1gUuaLhVqqhs=,iv:AyNafWpF7dn/0bJYUYoi/Ukki7WaRzzMNSB93yJWjdw=,tag:U8eNkda+uZof1wlhHSIXbg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
