# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:BisSrI5+B0xxmC2dpHmCBpVBzAzIpPXKmHt06z6mgDE=,iv:O99z0EXZLp8gLDCKJcJPp/iG62czrOh0dbzrJlnJu7s=,tag:vCSoSX4mfaUlh0g1y6eM9w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOTM3em14YjB0RFVGV2Nx
        Zy9ZdDRzUWxhdHJyaTExY1BjSDc4RTM2emxnClhIMVYyZ2Y3Rjc1R0FlMEJOdDU0
        RVJMdVJyeFRjc2R2R3ZNbmhRRGpHTFUKLS0tIHRORFZJYlArM0dnRFp2dUc1bUs0
        ZHB2NFJXeEp4QzA0anJ4UnRacEZ2RkUKhXYZP/35sBZtnPUECd4x2YjC5KiCid02
        VSaEQS8evDhu4DAPjtrMI2VUzt6MTUw+n3G+t2NGMUKn7ISeEvpJ0A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:09:48Z"
  mac: ENC[AES256_GCM,data:14L2POg7st8+rayh3Twi7NtvoSrcu5gUaj2iP0GCUJTPRLV64Ct8i4HXf4hSnQ6iJE0yYszq2IuLgkrGkH073D8UwTBe5AyJ8LwJTSPOp7o2UU8BxOhMBowQ5gpbZWXyRtK8mB1GKiDLl9ek+mkuslzwAuvoZKZ+0qdV9uHj8e0=,iv:7iRPVSH67I3VXPn2za3r1QkSQpzWGVZfo6K9EErHero=,tag:Qh0wb1bG58uvq1EAY/YtTw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
