# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:noQPL6mVuQoT8Vp56CRuvU0Bst4M7nBEie4XJzKw0X4=,iv:PrxFeIe86OUDKKqPUfucpXG+6fvcvX2mRzJCh59oz+A=,tag:SGQj5lBYOgio0+fyzkz0UQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbG9hNThoT013TGlCMnpP
        c1NnZG4yOGprc09NS09YWEFTeHZGdDVQWmk4Cm1QRjl1M1R1eDFwVVM5QWVvdnov
        YlQ3TEZnZUZ5NlEwbjRlRzFiWTF4KzgKLS0tIERUUDZ0UGplR3ZUVHBzaVdIamk4
        a0xxT3k0aStUSmVKMERYZVJQNTM2TmcKWfC+pIn8sT3Q17yndscrqmM+trpjsSiO
        SVxqd0L0Wj46/GgeshT9t9r5D91m+9b6SOke/06DxOH4jvPvKHRBFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-29T21:32:18Z"
  mac: ENC[AES256_GCM,data:lDadTmEsdF3M1iluUehdVNlgtbTxdkOdJYFBtREmSOBEEA3iJwqpyhcS43HBdinnAkhAJvsddH+HuCp3T0dkwhNGYfZd1LJXsIzbLtRCHYTMkswPDKaxdu95X4ftSaICgwyknN9WXK5ad+I/OfUmBkDYvMAaDv1cNp96LAF4zMg=,iv:PVyOJ2jlk01DFMpr1llYV5oJEsBZM6Y3gvCfVKJs4dQ=,tag:trQmFnTUzPXbD2EO6C5KIQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
