# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Vpxy06gdaIQsL78kDasBp4yLTpEAPpYjIPuugJLIEMc=,iv:BOiqrPWFVG7xJZ5ZpdM7zaknyJ9dn+hQcaf/GZNoOwk=,tag:DDeJI4Ba5KSmj096pUm7ag==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV0N3MUhVZUFoQTZWRjgv
        WDE1UjBYRnRpTHJzRTB6eVhOU2pDZjF2WGowCjJNMm1LelUxYzVjTXpGTklzL084
        bGMvRm90aXo3NUZ5UklsNzdiRkp5NUEKLS0tIGE0WUNTVmdOZlpyalpIYmJGMXhO
        Mi8vUzVFZDRZUTlZeGVJU2xnS0ZkYjAKL1YMLe2NzMnZrK81BZohHwmVg6mZuhuU
        v+HfPf+0MBZfh2usfQS9lzLHAtbJSRpmq+ncFIT/r+N9ZTj0zjbylQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-21T16:39:33Z"
  mac: ENC[AES256_GCM,data:7hBQpE+Twvfu1DS3TMSxvjy0YH56jatmjzkIzzKxhXeNodQg1eD8RHEr5K6g/rDYnL9vbjyX8jcPqV68xSJNLVgHHzUutqyjOvM3YbtYuwTcbV+hh4lUSBc5u1xu/MugfWYArmt8oE2MrK1jNHvId0OkJiR/8QNo44/XlKD4G2o=,iv:EqOCVWWjOFROW5hD4fnlngKUZKxlCeA10oGIstoM0LM=,tag:CfPalVifjjX1qFJJtgat3A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
