# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:W+13l9wdo2bVuMW2ZzIVJF+XR/Luka87wMiqFDGcQG4=,iv:zsoYh3I05tutnQrU0/7qNSqXfNDmJOdf/7FAlYTR3Yk=,tag:anUCalFnZ9GbMeFWRCoJbg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWk1wbHRRR3hma09xSHhN
        K0FtL2RWNkVqWFN6bllrS1pyOS9OSjJLQVFnCnAwbWdQQ3BQR0sza2pJaVhOdjBl
        a0RQSUExT2xuV3IyVUs5cEJlNmZ4ZVUKLS0tIHZqWERZODM1VzU5SmJTQUNPZ1dX
        WjFTNkhkditiRVBvaE52cUxPcXNZbkEKRsbia0g/DBHP9crv1vGTdQAx5c/fLdqa
        ErRtOMS/JHJDvHKyhDt084aznseIxuPwrRFNM74bo+xVTuayIPHknQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T21:58:14Z"
  mac: ENC[AES256_GCM,data:hDToQHPK8POZlQcEfdHovGNcIB1tKMpf+NUuiymk+PIR9+lP6jljlZ2/qhAar7GfJMUMKGFg1198I5gAnJDAWqRKa9nze1GDXRjW4jiOmsDxtcgGV8zUx96eC1ytqoAnqTKYmY7kfaB1MKGZ8iYqgHwqPA2VMeg696r82ptfqtY=,iv:UUrOi1yzpZxzFH7SJtAgVrhVPBHsI5MhfPJEWPoiEfk=,tag:t9bFHJK3VaPwitDAnYRk0w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
