# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FqXNiVDSovfjIeCl95dfODQ5udhPrLvJGXPc9AWZnqQ=,iv:R1yPdfXwpxzWzRByXWIWLb+BA0OTIrcImzzWAJWDUjE=,tag:wBnE+ChWNuXgd8uHt+HWGQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYckFvU1hvb2pnWHNoTHNF
        cFFnaS96Z1hwSDNjR04vRVd5RXk0RUdxTURzCmtLWHBTMG9kL1RIaTQ4VDFGZEhC
        KzNIZUE0MmozR2FpOVpvRGJielZuaWcKLS0tICs4cXRia1ZLSHM2YUlaNlpZdWZW
        a3hlMldEVzBOeTdheWR1aXFMSXNYYXcK9KX5v6kEoFEF4zox7+FfTfH5KbSa8Iio
        W/3KUFXvac4HkK86RORMdzYk5Tdc7d6Kmb/RcYxmQo30U2/A1SFH9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:37:12Z"
  mac: ENC[AES256_GCM,data:YRyI+NL8T9edy2wR0mlKgIH9TdPoBnUjlg3pb61BmDz8Tx/CmHrwAKjTmotWi2PuD6wJES3BcirgtONpllJ73ow6sn020JttFZgXhQ3SeVdvvyT3rFR9B75fADtSfw4VAAJ0YkkjhFjPMu/UrBDW3gOKOHgGBzWW7JlactIGYNk=,iv:20p5bUdL6ffKbGG0sO9D6mIcfBX7O/2+y/cVoSozatQ=,tag:hlQqH1lblNauklpaJah/fQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
