# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:9PMJsm270jUJC8a9l2aa8fttgqM6eCJt40CfLUS9kHg=,iv:oo8nGLxSXO1v7zRSYaMhLzfoT2UUG377ikQZ2pSBmw0=,tag:Q3dQ5z7mFPG4p+KPWn13YQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM2ZaQ0FXZktMYUl3T2xE
        YThIMzdSeFNvT2IvanVWZ2VNbGtlSEdMb1RvCkNhOGt4dEducjR2WDdxcDh0NVlV
        WExuemxHQ1pZeU1DWU9Kd2NLSSs2RVEKLS0tIGQvQ3FDb0dUVk16ZEFlWkw5dXlu
        Tm41SUdQSGsrZUk5NXAwWDgveVVYa0EKt25DU068bc9RCToLyFt5h8Eh8a9HxhES
        /LXKfxpBvplfEi72WiCWEeBYZYcRkv+BM+RcbBHOXxgVfK0Y/L+5jA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T10:32:15Z"
  mac: ENC[AES256_GCM,data:q+7ZNOLQnfXr0ayq7ngi8hAW0bk//jOOZoENe4oByqsBQmR2wwGJlrKTNnzOT6yNHEzECegwg7ChyyYbjw9/sfvXgq4amVTMUbH/igejgZYe+Q/B+OFPL3/FXbDMnfjtHD1eu8Z7j+hESHQgouUog0ePajOLnmaLIcrcXxb/6Ag=,iv:TdpdzvoU4zMMjm4UfncCYdGzvDs9SbiqVZCVBtKpPzc=,tag:E29jauGPEx4ZK3wiKG1LJQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
