# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:SoPegkkRHgbuvFfO4jUVZ/YHa6KT1iAeqvnVSERpQG8=,iv:qeP+DSYVMlGQaSBLDLaEuOnrzxyqLmOqFTaER0iw1rY=,tag:bpoyH0tEfK+kC93pSicQTg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNTVFRStzcnNBZE9tVW9S
        ajJvOEorYmNDSng1VERNVU9yZ2VleldWbG5NCjcvdFhaNXFNcEk0UFhWbytOc21k
        Y3EvbXB0MUpEZ1dlU3Rycm5OQlNZcHMKLS0tIDdLRnJiMGVOeHVDbmZmcG1ZZHhw
        Q1JOMW9DTlFLdnZ4Sy9PMzJzNlRDSDQKGM6U0lOS4m2+zhsyPlYujfgC7W6oURO9
        eyeXmDxjA9Cp9zGQKLd02qkOT4pllnFei/DD4aCHy0OkoNEdWFj5kg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:05:27Z"
  mac: ENC[AES256_GCM,data:OCwaC6rf0woW83eS9pY0QyIEKilgit5HdAHOPtnikN68VBSdNOqFtElxvgtw5Ev6358HbERSnkWHibZvGBKfzI2BGZSMHNeVNk6UDSGw7SwUlsYzHofUlg/BCFIST/6njtrEc5r6yOsfDMfEBo8TJIRfjEmaNLsqxzNPPG/WChk=,iv:8TyrCf44n0/ghzXBNDzWOoh9xVZhy2hakIt1R8ktCiA=,tag:oogR6+LR9tjGILQa7d7bxw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
