# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:y0wODA8dY1wiGCSOZVUAJ4U4MrU3gRN8JSeRkDPzQnA=,iv:tSWHaBW0L6byNfj/GVwshKmSS6xD2Pv+XPbFbsl6M7U=,tag:p85EmG6RUbCKMA1iAdwV4g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNnQzakxYdEF3bm5Bb2ZJ
        WjJpb2lMbEgxb0I4NU9EMlVWNWdRZXFFVlhRClJ4ekRzQlErUVpkTE1RZjRIVjhD
        MVYwa2Uzc0dIWmN4NGNqWjd1RTVLYnMKLS0tIG5lQlJLdjFvZmtaK29Ia3NkNFBU
        dmcxdXdNdGhBTVlCWjE3b2xwaUwrYzQKvYIOhMb5QOqVHFpA5Z1r7XFQIJ444BEe
        3C1uuEgprRXr/qrnsmUszwWLolwfvtfgmeCl1EgMmm6XhnoF0l7kIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:19:47Z"
  mac: ENC[AES256_GCM,data:kWHo4Gjej1wQOGH8p4K4V+V8uNRNG4FVWh9lKgRxlb11j5DoJnwFH3A/ZqL4rZvx5LAntrQifz3WVVZZ/ejRRNoLZlP8OQsvY8bm+56Sr8kb1QYFiVTC5fBlJ7PsovfL55mdFfumc2TYQ7IBZC/Sbhey49zLQtylshG2XOlqG9g=,iv:TlH2voqKryopIN1OzUyFy4Bzfk0WfYafgCSRRJL4nus=,tag:uNZ12fsXn7rrH+ccVOkBiw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
