---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-redis
    - name: cluster-apps-cloudnative-pg-clusters
    - name: cluster-apps-nginx-internal
    - name: cluster-apps-nginx-external
  path: ./kubernetes/apps/security/authentik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik-ldap
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security/authentik/ldap
  dependsOn:
    - name: cluster-apps-authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
