---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: &name doppler-connect
spec:
  provider:
    doppler:
      project: k8s
      config: prd
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: security
