---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/databases/cloudnative-pg/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-clusters
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-operator
  path: ./kubernetes/apps/databases/cloudnative-pg/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
