connectIPVersion: v4
upstreams:
  groups:
    default:
      - tcp-tls:one.one.one.one
      - tcp-tls:dns.quad9.net
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
  timeout: 2s

conditional:
  mapping:
    ${SECRET_INTERNAL_DOMAIN}: tcp+udp:10.17.0.4
    ${SECRET_DOMAIN}: tcp+udp:10.17.8.99
    8.17.10.in-addr.arpa: tcp+udp:10.17.8.1
    0.17.10.in-addr.arpa: tcp+udp:10.17.8.1

bootstrapDns:
  upstream: tcp-tls:one.one.one.one
  ips:
  - 1.1.1.1

ede:
  enable: false

redis:
  address: redis.databases.svc:6379
  database: 2
  required: true
  connectionAttempts: 10
  connectionCooldown: 3s

blocking:
  blackLists:
    ads: # Ref: https://firebog.net
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://big.oisd.nl/domainswild
    malicious: # Ref: https://firebog.net
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://bitbucket.org/ethanr/dns-blacklists/raw/master/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/RPiList-Malware.txt
      - https://v.firebog.net/hosts/RPiList-Phishing.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/
    native: # Ref: https://github.com/hagezi/dns-blocklists
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.amazon.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.apple.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.huawei.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.lgwebos.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.tiktok.extended.txt
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.winoffice.txt
    other: # Ref: https://firebog.net
      - https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
    suspicious: # Ref: https://firebog.net
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
    tracking: # Ref: https://firebog.net
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt

    noblock: []

  whiteLists:
    ads: &whiteList
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
    malicious: *whiteList
    native: *whiteList
    other: *whiteList
    suspicious: *whiteList
    tracking: *whiteList
    noblock: []

  clientGroupsBlock:
    default:
      - ads
      - malicious
      - native
      - other
      - suspicious
      - tracking
    10.17.8.0/24:
      - malicious
      - suspicious
    10.17.0.5/32:
      - noblock
    10.17.0.12/32:
      - noblock

clientLookup:
  upstream: tcp+udp:10.17.0.4

caching:
  prefetching: true
  prefetchExpires: 2h
  minTime: 5m
  cacheTimeNegative: -1m

prometheus:
  enable: true
  path: /metrics

ports:
  dns: 53
  https: 443
  tls: 853
  http: 4000
certFile: /certs/tls.crt
keyFile: /certs/tls.key
log:
  level: info
  format: text

queryLog:
  type: postgresql
  target: postgresql://{{ .POSTGRES_BLOCKY_USER }}:{{ .POSTGRES_BLOCKY_PASS }}@cnpg-blocky-rw.databases.svc.cluster.local:5432/blocky
  logRetentionDays: 10
