connectIPVersion: v4
upstreams:
  groups:
    default:
      - tcp-tls:one.one.one.one
      - tcp-tls:dns.quad9.net
      - https://cloudflare-dns.com/dns-query
      - https://dns.quad9.net/dns-query
  timeout: 2s

conditional:
  mapping:
    ${SECRET_INTERNAL_DOMAIN}: tcp+udp:10.17.0.4
    ${SECRET_DOMAIN}: tcp+udp:10.17.8.99
    8.17.10.in-addr.arpa: tcp+udp:10.17.0.4
    0.17.10.in-addr.arpa: tcp+udp:10.17.0.4

bootstrapDns:
  upstream: tcp-tls:one.one.one.one
  ips:
  - 1.1.1.1

ede:
  enable: true

# redis:
#   address: redis.database.svc:6379
#   database: 2
#   required: true
#   connectionAttempts: 10
#   connectionCooldown: 3s

blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/lists.php?type=nocross
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
    trackers:
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    noblock: []

  whiteLists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
    trackers:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
    noblock: []

  clientGroupsBlock:
    default:
      - ads
      - trackers
    10.17.8.0/24:
      - noblock

clientLookup:
  upstream: tcp+udp:10.17.0.4

caching:
  prefetching: true
  prefetchExpires: 2h
  minTime: 5m
  cacheTimeNegative: -1m

prometheus:
  enable: true
  path: /metrics

ports:
#   https: 443
#   tls: 853
  http: 4000
# certFile: /tls/tls.crt
# keyFile: /tls/tls.key
log:
  level: info
  format: json
