---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minio-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-dcsi
  path: ./kubernetes/apps/storage/minio/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-minio-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-dcsi
    - name: cluster-apps-minio-operator
  path: ./kubernetes/apps/storage/minio/tenant
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
