---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app minio
  namespace: flux-system
spec:
  targetNamespace: storage
  dependsOn:
    - name: openebs
  path: ./kubernetes/apps/storage/minio/standalone
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
