---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openldap
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: openldap
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      ldapDomain: "home.arpa"
      existingSecret: openldap-secret
    customTLS:
      enabled: false
    replicaCount: 1
    persistence:
      enabled: true
      size: 500Mi
      storageClass: local-hostpath
    phpldapadmin:
      enabled: true
      env:
        PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
        LDAP_SKIP_DEFAULT_TREE: "yes"
      ingress:
        enabled: true
        ingressClassName: internal
        className: internal
        annotations:
          hajimari.io/icon: mdi:account-lock
        hosts:
          - host: &host "phpldapadmin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    ltb-passwd:
      enabled : false
    nodeSelector:
      openebs.io/storage: "true"
