---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openldap
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      chart: openldap-stack-ha
      version: 4.2.5
      sourceRef:
        kind: HelmRepository
        name: openldap
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      ldapDomain: "${SECRET_DOMAIN}"
      existingSecret: openldap-secret
    customTLS:
      enabled: false
    replicaCount: 1
    persistence:
      enabled: false
      # size: 500Mi
      # storageClass: local-hostpath
    phpldapadmin:
      enabled: true
      env:
        PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
        LDAP_SKIP_DEFAULT_TREE: "yes"
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:account-lock
        hosts:
        - phpldapadmin.${SECRET_DOMAIN}
        tls:
        - secretName: phpldapadmin-secret
          hosts:
          - phpldapadmin.${SECRET_DOMAIN}
    ltb-passwd:
      enabled : false
    # nodeSelector:
    #   openebs.io/storage: "true"
    image:
      repository: bitnami/openldap
      tag: 2.6.8
    service:
      type: LoadBalancer
      loadBalancerIP: 10.17.8.6
      annotations:
        io.cilium/lb-ipam-ips: 10.17.8.6
    initTLSSecret:
      tls_enabled: true
      secret: openldap-tls
