apiVersion: v1
kind: Secret
metadata:
    name: openldap-secret
    namespace: security
stringData:
    LDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:5DFAiEQFGjfxSGDGco8SEYHJrd59gBjzTniE3/RQlwg2DRD97dxc,iv:G4eTrtqXStfD02U3q+hjY+RecIQ65YVs5NJISqdzqe8=,tag:h7IsIcGroGnoliXQcukeNg==,type:str]
    LDAP_CONFIG_PASSWORD: ENC[AES256_GCM,data:0V/qCYBz9r7BlgWmLusAnQpAe1d1m3UkBVQCgo9SF6xG7z7yp4Q=,iv:AEk1Ezhwg2V1FiTMwuyDCdjVxWdlPneiuKQGZDJSEQg=,tag:9wXoj9usK+fAOND9vdyedg==,type:str]
    LDAP_USERS: ENC[AES256_GCM,data:VCuadPiY42My5P8=,iv:lJkozlZQhsa5dK78nuaryHrfjzjM3LAbn1zQcY2WoGA=,tag:6x4A0G3ZNhZe9/datebbYw==,type:str]
    LDAP_PASSWORDS: ENC[AES256_GCM,data:7VpzVOJ+KPERXEgdVUJmQSJkAcs=,iv:jvQIPX+6shQu5t92qAgHuFJyOAGML9L4zYgXrJ72d3k=,tag:RKn9kMZbtFGWy5jZMM+pMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbXdrVFhwb2VtZ1hRWjFW
            MjVWUEwxOFo1SW1rOW11eC9TYjhBbTVlUG1VClkwR1FINGFSVUIybjZuYXRiQVE1
            c1ZZTFd2UUtrUlFBc1lZU2JmejdvblEKLS0tIG1XaFp0VXVESGdvOFRKMU16WWMr
            SSs5MUFINjhmWVR6ak93Z1UveUsyOFUKwMgfUYsxXvNa8EZOfuDMVHof3kSuYQtJ
            sS4tjVdCYoF2hePIlCHa3yPAbJNdzTq0SIDZCWkdZxOOlYePt54THw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-30T17:41:03Z"
    mac: ENC[AES256_GCM,data:kQkAyMoTa5ELxrqxOWtmAAJnZky3lJCzfZ5ma9VjzPzLMBXZk6NkKATQJ+TkzaVBxQMOi/GVjWN3p+SjkwimWxdLg2ecyCKWsRp71oQ9Y6Pk48BRGPng+IyTrV1GpnT2LZJdt5v2UMRC0KarZf377QMsBjterTEhlRxHg80ZJPs=,iv:Ry2LogO8Jy3Iz3TipgFUn3DG979jkHI1i3y5rHqdwM0=,tag:ndnl/GRFBJFa0n5xtNHzcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
