---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap
  namespace: security
spec:
  secretName: openldap-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 384
  commonName: ${SECRET_DOMAIN}
  dnsNames:
    - ${SECRET_DOMAIN}
    - '*.${SECRET_DOMAIN}'
