---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 3.9.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
      interval: 10m
  install:
    timeout: 30m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    legacy:
      enabled: false
    localprovisioner:
      enabled: false
    ndm:
      enabled: false
    jiva:
      enabled: true
      nodeSelector:
        openebs.io/storage: "true"
      csiNode:
        nodeSelector:
          openebs.io/storage: "true"
    openebs-ndm:
      enabled: true
      ndm:
        nodeSelector:
          openebs.io/storage: "true"
      ndmOperator:
        nodeSelector:
          openebs.io/storage: "true"
    localpv-provisioner:
      enabled: true
      localpv:
        nodeSelector:
          openebs.io/storage: "true"
      deviceClass:
        enabled: false
      hostpathClass:
        nodeAffinityLabels:
          - openebs.io/storage=true

