---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-pgadmin
  namespace: flux-system
spec:
  path: ./kubernetes/apps/databases/pgadmin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: cluster-apps-cloudnative-pg-clusters
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 3m
