---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app blocky
  namespace: flux-system
spec:
  targetNamespace: services
  dependsOn:
    - name: redis
    - name: nginx-internal
    - name: nginx-external
  path: ./kubernetes/apps/services/blocky/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
