---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: freeradius
spec:
  secretName: freeradius-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: "radius.${SECRET_DOMAIN}"
  dnsNames:
    - "radius.${SECRET_DOMAIN}"
