---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-node-problem-detector
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/k8s-tools/node-problem-detector/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
