---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:

  clean:
    desc: Clean files and directories no longer needed after cluster bootstrap
    cmds:
      # Clean up CI
      - rm -rf {{.ROOT_DIR}}/.github/tests
      - rm -rf {{.ROOT_DIR}}/.github/workflows/e2e.yaml
      # Move bootstrap directory to gitignored directory
      - mv {{.BOOTSTRAP_DIR}} {{.PRIVATE_DIR}}/bootstrap-{{now | date "150405"}}
      - mv {{.MAKEJINJA_CONFIG_FILE}} {{.PRIVATE_DIR}}/makejinja-{{now | date "150405"}}.toml
      # Update renovate.json5
      - sed -i {{if eq OS "darwin"}}''{{end}} 's/(..\.j2)\?(..\.j2)\?//g' {{.ROOT_DIR}}/.github/renovate.json5
    preconditions:
      - sh: test -d {{.BOOTSTRAP_DIR}}
      - sh: test -d {{.PRIVATE_DIR}}
      - sh: test -f {{.ROOT_DIR}}/.github/renovate.json5

  reset:
    desc: Reset templated configuration files
    prompt: Reset templated configuration files... continue?
    cmds:
      - rm -rf {{.SOPS_CONFIG_FILE}}
      - rm -rf {{.ANSIBLE_DIR}}
      - rm -rf {{.KUBERNETES_DIR}}
      - rm -rf {{.K0S_CONFIG_FILE}}

  force-reset:
    desc: Reset repo back to HEAD
    prompt: Reset repo back to HEAD... continue?
    cmds:
      - task: reset
      - git reset --hard HEAD
      - git clean -f -d
      - git pull origin main
