apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:yHOl89pWBpvamUXNsa6vIZFK8ZCJoXAyO2fF586naYfKoj4zZqKBV4bTMHGIpPkyLpCgayeZWNJ/kErk,iv:u9cOAAAB5LiyHSm8UbpLVOmF3e9H/Q3jv2MIHAWTkOA=,tag:5DCmgkXgHmtJeCyvjJFY1g==,type:str]
    username: ENC[AES256_GCM,data:feH+Wf0=,iv:ZwLFnqBsVxC0QMqC/ZODKC2pLZHcUnWK5pldOuVWVus=,tag:v1GSrgyCFiWWD2IQjBQkvQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1blhQWjJRNTlHdER3ZGVn
            S1A0SWVPU2RONEFLeGhZVU1OUk1LTXhWM0RBCmcxbXVqMXd5T3VBYnpCMk9qN3BZ
            Nm1RbFBMRUUxaVhNK0cwdnJaWHljSkUKLS0tIFBTYWhhVm4xNThTK0RUeXg3Tkxo
            d2JOVmV2R3dwWWt1Y01nRnNGUHF2cncKOexkEWh7eUooJ6XZ6gitCvJoxX7zQkLm
            6WEoQxr7wf5wwly8nGxVVNVsrRyK3YMg5JgELkJq3iPV22Aj6V39OA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T15:39:17Z"
    mac: ENC[AES256_GCM,data:d306xEnyqxy27tTT6WQJD0js4EBCitVklUKU+327Qx0qrMfvDJe56otILx9SqjiHtg382eTEyS9A6Jt7vfhO4RbwwlTlQkAGjEMcmLZxfhQaI2WdbG5C75du2inCfeA8qfVQlP3peQ1Yd3hIwjSCMxt5zYR3ycSebJhiHHNQZN8=,iv:KRWyWxUY93IjW+SECQCzOHmPuF9k8++dfeV4CLz+1Jw=,tag:JDMLdti+hYknZg7Bj2k8Wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
