---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app searxng
  namespace: services
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: redis
      namespace: databases
  values:
    global:
      fullnameOverride: *app
    controllers:
      searxng:
        pod:
          annotations:
            setGateway: "true"
        containers:
          app:
            image:
              repository: docker.io/searxng/searxng
              tag: 2023.11.1-b5a8ddfec
            resources:
              requests:
                cpu: 50m
                memory: 850Mi
              limits:
                memory: 2048Mi
            env:
              TZ: "${TZ}"
              SEARXNG_BASE_URL: "https://search.${SECRET_DOMAIN}"
              SEARXNG_URL: "https://search.${SECRET_DOMAIN}"
              SEARXNG_PORT: &http "8080"
              SEARXNG_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: searxng-secrets
                    key: SEARXNG_SECRET
              SEARXNG_REDIS_URL: "redis://redis.databases.svc.cluster.local:6379"
    service:
      app:
        controller: *app
        ports:
          http:
            port: *http
    defaultPodOptions:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: *app
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: mdi:search-web
        hosts:
          - host: &host "search.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: configMap
        name: searxng-config
        advancedMounts:
          searxng:
            app:
              - path: /etc/searxng/settings.yml
                subPath: settings.yml
                readOnly: true
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /etc/searxng

    configMaps:
      config:
        enabled: true
        data:
          settings.yml: |-
            use_default_settings:
              engines:
                keep_only:
                  - arch linux wiki
                  - google
                  - google images
                  - google news
                  - google videos
                  - google scholar
                  - google play apps
                  - duckduckgo
                  - brave
                  - startpage
                  - qwant
                  - qwant news
                  - qwant images
                  - qwant videos
                  - gitlab
                  - github
                  - codeberg
                  - sourcehut
                  - bitbucket
                  - apple app store
                  - wikipedia
                  - currency
                  - docker hub
                  - ddg definitions
                  - duckduckgo images
                  - bandcamp
                  - deviantart
                  - tineye
                  - apple maps
                  - fdroid
                  - flickr
                  - free software directory
                  - z-library
                  - lobste.rs
                  - azlyrics
                  - openstreetmap
                  - npm
                  - pypi
                  - lib.rs
                  - nyaa
                  - reddit
                  - sepiasearch
                  - soundcloud
                  - stackoverflow
                  - askubuntu
                  - superuser
                  - searchcode code
                  - unsplash
                  - youtube
                  - wolframalpha
                  - mojeek
            engines:
              - name: brave
                disabled: false
              - name: startpage
                disabled: false
              - name: apple app store
                disabled: false
              - name: ddg definitions
                disabled: false
              - name: tineye
                disabled: false
              - name: apple maps
                disabled: false
              - name: duckduckgo images
                disabled: false
              - name: fdroid
                disabled: false
              - name: free software directory
                disabled: false
              - name: bitbucket
                disabled: false
              - name: gitlab
                disabled: false
              - name: codeberg
                disabled: false
              - name: google play apps
                disabled: false
              - name: lobste.rs
                disabled: false
              - name: azlyrics
                disabled: false
              - name: npm
                disabled: false
              - name: nyaa
                disabled: false
                categories: videos
              - name: searchcode code
                disabled: false
              - name: mojeek
                disabled: false
              - name: lib.rs
                disabled: false
              - name: sourcehut
                disabled: false
            general:
              instance_name: "My Search"
              enable_metrics: false
            brand:
              new_issue_url: ""
              docs_url: ""
              public_instances: ""
              wiki_url: ""
              issue_url: ""
            search:
              safe_search: 0
              autocomplete: "duckduckgo"
              autocomplete_min: 2
            server:
              image_proxy: true
              http_protocol_version: "1.1"
              method: "GET"
            ui:
              static_use_hash: true
              infinite_scroll: true
              default_theme: "simple"
              theme_args:
                simple_style: "light"
            enabled_plugins:
              - 'Hash plugin'
              - 'Search on category select'
              - 'Self Information'
              - 'Tracker URL remover'
              - 'Open Access DOI rewrite'
              - 'Vim-like hotkeys'
    # NOTE: Search engines disabled:
    # - archive.is (too many requests)
