---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ./secret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: searxng
    files:
      - ./resources/limiter.toml
      - ./resources/settings.yml
