apiVersion: v1
kind: Secret
metadata:
    name: searxng-secrets
    namespace: services
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:bdeRs44G8gKQGo0q+xX2eY1yugrv,iv:01PQPrnZ6XGsKYCfmzxTqBJS4tl+nrdxP1fRs3WfyrA=,tag:+DgLgukh36AnbeZ0O9SGBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRnIwUTI5aVdkOUhtQmxn
            MU1LVzRqb3U1cFN1aUdNUzA3MHVVamNCZUhnCjQzc1dxc2V2eklnMjY2U2VOeFVv
            L0h0YXlZcC9TUUNhMkIwWHRPdTFBUE0KLS0tIHpaQ0dBS0V3U2dkNVEwRURvSlVN
            ZGhmaFRqeG0zVmkxcEZBL2pwci9LK1EKPv5ylxL62MtSdM7qZNlq/7v20tlVWBOL
            /GRJOLg6eonEpV/YHkXFYSaohuaSMnv7FvkEQJkgr2jVjQKPf9rp+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-15T10:31:08Z"
    mac: ENC[AES256_GCM,data:Jf1J2dQbKMb191Vu6exLclXtU9SrVOwEGJs5Hj1w88nmYH5thjmFXk12fEoY9W9HpBmWgetdHRlaZ1fEmJcVShWIxIKp81nJVKrWuuEs5XCMROKH+qM8KkIo2b5rOoZtlq7C8fasIYyZ3azIE+Isucy/86OlvU/yaMpLliiLBKc=,iv:T+O0WFdPDvnNMEg+2sjDFK/GnZGX4L/NuYVUzICB8ao=,tag:bajNo6dFumL2zDtGlYRdEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
