apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: searxng-es
  namespace: &namespace services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: searxng-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET }}"
  dataFrom:
    - find:
        path: SEARXNG_
