apiVersion: v1
kind: Secret
metadata:
    name: searxng-secrets
    namespace: services
stringData:
    searxng-secret1: ENC[AES256_GCM,data:rcYI4NMcUzb2Ypl8RBhia7TA7MWo,iv:C/qXX2PexoN8iqgVNC4CxLoCdJ67+HgxZ/uyt/+65Tg=,tag:9IkNkRuFA4c2OAaFZX62GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRnIwUTI5aVdkOUhtQmxn
            MU1LVzRqb3U1cFN1aUdNUzA3MHVVamNCZUhnCjQzc1dxc2V2eklnMjY2U2VOeFVv
            L0h0YXlZcC9TUUNhMkIwWHRPdTFBUE0KLS0tIHpaQ0dBS0V3U2dkNVEwRURvSlVN
            ZGhmaFRqeG0zVmkxcEZBL2pwci9LK1EKPv5ylxL62MtSdM7qZNlq/7v20tlVWBOL
            /GRJOLg6eonEpV/YHkXFYSaohuaSMnv7FvkEQJkgr2jVjQKPf9rp+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-03T12:33:15Z"
    mac: ENC[AES256_GCM,data:di8hO0tn43kMSRr6vN9PeSUgYMoGtLodBH2WgYZLNcVimKtRNeFn7uYfEJT0AX/u+EEeOg0HflmCSybdjnLFP13dW9TlDX4yy4mzWbWvffPR7MfiOeQOgqKJjNTSyup2Ar/Hv1X2nXcce3iT0+hdAcfKeP5f4X5s5ZWJYMhOrBU=,iv:LzETF8wBmSiihmJQg/sPqA34ScqkGL5jD6eDq0sbBw0=,tag:RwyNcr3GLqK4C5DENqFetQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
