---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-k8tz
  namespace: flux-system
spec:
  targetNamespace: tools
  interval: 10m
  path: "./kubernetes/apps/tools/k8tz/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cert-manager
