apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:3l0D2iQ4Oc+HqctRUjob,iv:r9P01V8VtuX+uTfvvSL7s6zgLCcGp3EQKKJKD5GscNE=,tag:+bHfIKN7rvZ9zRkaHeef3A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraXBudU5nTW9maWdJL0VE
        ajdWb2k0Sm9pZWk1MFpvWVIwY2dPUFlvcVNnCmdsZlM2eEVxd2JPeExkN1BBeDQy
        a2pQWVh2YVo4aEppSzl1NkFvaWFzSm8KLS0tIHpNTU9MLzJ0NjM3TmxPZWh2Unoz
        V0JzWkpaWUxtc1hEVUt4ZU5veWJJNDQK8ra3Es/ujATyjTwdCFBuKWcsgpsDbTJF
        Z8z2om2ITLjk0gMO2yJRMu8TRPff3YymJfSrA4DxUd3ylMXffrpg9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-08T15:20:58Z"
  mac: ENC[AES256_GCM,data:G0YdL0VTTFNncFoOG8Abv7O4Uo5VKif8B57my7c6QJTi3jNzhWp1HJweenR101dA3B1uuJ41JlPrqOpNzua5kmg2wNy8aMwK14eenmbLf34N7aIGbz/eram8u+ukvRPVIc9Px0zr60KnZ2ciVZHgU+oYf8RIpdUiY/M8/VWC+fw=,iv:mwuYEoNv3/9Acta1Tk8MGppHdVO5/GvKre/Ah+etXbI=,tag:GA3n38ZKxoL5VT3RzMAdog==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
