# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:UVNJZA7j1GP7Rumb9PPSEqyuHK1PdCrM+S98UQCDaoevOaaLtUlTjQ==,iv:65rswtzGvOiMliqybq/TJI+lQgsUYA3MwRLot/SLpUs=,tag:m2D4s2RPJeQIbqueua8rtw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUFc5YmlncUdyY3RRcmpN
        UDhTbTVmdUdWQXVvbVlLQjFGWFl0dmQrbUE0Cmh1dHEzSTN2ZWpGZDd6TmF3RFNK
        L2xqZmhlRzFNQTZOY09UNG1oYXBDU0kKLS0tIFQzaTE1eGJBNFowNTB4dzJEMFRM
        Y3puRFRsMU94Zm5kdkl1QTZYckRWNlkK1IU80Pt0zUfYfV0Bm7RyyacttK4ra/22
        LIcz/S9rGgRxwfaK4OvN304hf5M2j6TZJDUiJBSqfAhPPYYLupc0wA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:09:48Z"
  mac: ENC[AES256_GCM,data:g5dBFahmAQVTzBAUsKU80vKKlwPuZ77b/IHou4cn3zb4kxc5jBgS95JzWMkElnPTan1RJPn1vDFiB1585q7t5zigtrMiQ8cPzpAcFQc/x/c5MkkItGgZB9evM+AT/5hPLWdR3ef99UrMyhjX9FR/5sEIpFQJlwME4juUYSHNEzY=,iv:WFgSqmwBBFr06DzaBNkVphz+q3LvKk3D3uGsrf1piSo=,tag:9NV+YSM/Kvu72OmGlOcYtA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
