# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bLUeUA2HmZvifCeuLvKyO0YFTRwEiLWFcm4+s7HALyyzMyE/fCd+pw==,iv:6r+8/y5c7sv9Hgh1DhaAoAje0LlWCjkgY2Um8ExLJ8Q=,tag:mmU+vpUDV6xLHTZtFkF0gA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOEYyeDlkWVp2STBJbUEv
        TENFSGxuSHBXRmtMMmxZYUQ2ZTBsRDV2NUhrCjdKZjd3WVlOY0lYSUo4VWxMdnV1
        SW1CbE5kREhDdm5NNFhBV0tDK2pJakUKLS0tIEVzQU1QVEVtbnBNY0hGU1cwejIz
        a1lKNzNKbk9Ya2o4K1RRRThWeXlBWWcKtPXY0dkPPxOtxO6+Bk4rImPq1tLGxr1A
        3zszM/BvV2rPAfvoC8xIM9acpJ9ZEI0wjTr8FeakH5NXyTlxNAbQ0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:19:47Z"
  mac: ENC[AES256_GCM,data:hq+Ak4ie5x18LqfeV2ts4Jx6B5Rju+2ljRvHvWsa17AkeNtTP1CL7K+s+9S17s+ycdbVgfWdU5CAreuZLYWwobt4Vtgw3AlGC0mCqZiqwsMhSIsMFeQZsS5AWKx1gIAiIMbZZHP32Sm/5m0CyC6niFAZhF4Jq8jQb/j6pAYKPs4=,iv:qIlyw+l/bIEO5noUKbCM27ekMNd8LXuHI6xu2tt6jjc=,tag:hReXvHJ5ZfkCWt71CjTQxQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
