# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:D6PA1JH+uaV83gwcFK+WBFMRyF7twr7B+vlYODYI0M72CCGZaGxS8Q==,iv:TW9OW98YpnZ9Kmj+Fzc/CCtEI4CxDSqHPKb8nXdZ/9k=,tag:ukADo+OYvPYUmSplYccaPQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZTNab2hPNHd6cW9Oc1Bo
        OFVnTzNnNlpmeThwcEptSEJkWkM3a0ZZWGtFCnpaTXE4eVNwQ3paWURtbnJqUTVW
        TDQvZmp0T2xSdi96UXV5cjZwK3NLRkUKLS0tIGVndldNZmNHdWNNT0NkMWxhalBL
        eGJkZVUxSXAyY3hxa0RsamE4Mm5NOFUKB3biYCB6uJ8OuLhIw2V7YaKqOVkssYLW
        fLSKYmmWT2eUMJygpQkdOUOLXill2P/hZplolgT1yi/Z5ZXOCa7THA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T17:10:52Z"
  mac: ENC[AES256_GCM,data:4R15p9+tkCc1U4HHES+21r3lh6Cx0ruB2ZW2RZe6kkhfktxQNceRpJ3Y58KjbYv6qjW/ibUjn3efddk40GIxIAHtL5VeXecF6dBgkzqop3HBweFh0BXqvwTHeE9IFyMiuIjf5eQBzbM/NguzjFMetqb2BTy2Vq/9Ccj4FGOr+Tc=,iv:oVW/6ooma6BzesoN2vE8QIhSYUruwg6uJ+gYViqXFzE=,tag:QsoiTrDM2lb6QiOOnUAOfA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
