# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:zOjnrGite7Z04xBnb7gUyro4nMk+YZfwRg9fMCMyWuKXfEYDo4ZQ2w==,iv:mSEZn99BBRkKX5zoGpI7TFfPA3RaTPOMYXgVzv7k9T0=,tag:5eVuoqKWqqwoZzNlYd98IQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQU9oTFh4dDJCdTF6NzJP
        eEljZWdlZi9IMERVL25pazhGeXN5b1lKMWg0CjBYNjZNa0lxeFBaSUZaWnI5OStr
        Q1ZnZ2lGUFFhWmVLbXkySkkvZy9tcmcKLS0tIGlxNUhvYU1TWmFORE5zcFpHNWI4
        M25WQ2RqZE1rbnlSNnRuQUJJdUxMVFkK7pOSl1bwM349iNeH0HNasDiioNiX6805
        UehFLtP4Flg+Kd/smX2CadUIf9OZe4pDGEQqeSEmKjYKWjlH/wdUZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T22:41:37Z"
  mac: ENC[AES256_GCM,data:3h1H/ik4EtsZT91NoDMM3FQqw8fqzgutWd83AAr7/TV38U/HP1CExhbg0NZSor//fivLGf6y4PtH12u01TJWJQU3fhDBEBbOrNYxK8naUP07nDsp+18IHqv9dx2QopfFgXDocqAjo4bF7H5q5HgpIZngcb06cNvPlYW+/wdNPuE=,iv:f5IgsU0BhSXuh1nlQIrzn2zi/876maIlE8lsl4vty0s=,tag:u2fVtqHegkjDZOg61BbZLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
