# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PHZNkKyfuv0Uw3j0q4+VWPNsqfoXD+EJ9N+uh6eM0UmkOYrLTSHNUA==,iv:5kKhcj3zhITLX8OUfhLd/pSBrxjuyVz7ldm/iXvthbs=,tag:5S/i80GdUoyn10VWuEdwUQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVTgxbmFvRWY2SWlpQmNC
        RjNDV1h5bG1iS3U5RjZ4bWI0TG9Ud21nUjI4Cmc3aWxvRC93OXBhTERNYUpWN1Rx
        VFhhTnREVm1SMk5hbTdGOGdEMllYZk0KLS0tIHoyckprQTFVNFVtKzFvSnpFNzVz
        YjluaUd3WERBUlc1Z1RHT3lDck9DNk0K9u//0J3bIThda3DAaFlSMP20Tnv2/vjl
        4EYy+2tgaiazYEUSMNGvfxShZregG+8rScTSmZwni1WzqIOlP6wqTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-26T18:37:07Z"
  mac: ENC[AES256_GCM,data:au1Svv+GltxRb5dJHgYPhMrI8u8kPVhFpl5exSK1oqp9jRrV4nWRXhmB/LsuMfG4xnJZX2Ubvys6yVnQZmKZRUE+Bk4wFOii7xdOiHv7stcTeGNS6EUbGOlHdpHiHBypVK2/mDmh8ZiPPQje34KmEGId43TcscPNVODvecYXTAM=,iv:VCHvTd28cQAuIc0KzdJvxO6opfp1egwkwZ57Pe8TTxY=,tag:ceE0yGAU6zuJGWi+c3wJUw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
