# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YPQfTmMNv7mKdVZipCBJ3z/v2YYv/ZeVcJ+nencY1aMgJjyIPfDA3Q==,iv:UZSXYAzjLgg1EFeuwe3sb5oe6e9MAGG22Ijpn5vch3I=,tag:E5gec8narWcxFxja33hxdQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVlg3VmdXcWJETG81N1p2
        dnp3YlJNVjdjQi9iazN5Zm9GWmZCaDNLajJZCnJKcWNEekd0alp4YWF1T243ZmU4
        QnlidG5ZMlhmUzBtb2d2SFgxVGlwd1UKLS0tIFhwNXB6eVZUdzJvczFGRFYraUg5
        Nk9zQWRDS2h3WisraS9hcFo5azFaaW8Kedap9MNkvecUE4FD9c7U2tJN80s+SiK3
        IKgrdKydDpRaII+BrFoRb4H+liqjlzu5FQk4Mocvd5W67yXJJayR0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:37:12Z"
  mac: ENC[AES256_GCM,data:V3++wZ7EpLFRwiKYT/7qTDCszbQVladSawA6uXrr3Q+NhlDhyngBuoWaXShcMPkVNykntP7k1M0vGVxMrEMY5AL9kfDzyVUVl5q0X3q8o3TsnGegvNtJYVZFHY0e4FTi1QJdiYf/axaIdBMVqDqW0ezB0mCN0MP7qegPm7dB4f4=,iv:WSkQOP1nXgo13VWOA/Hmut/42gPDs8v7B0Vpr7l6zfY=,tag:jqn7V8OS7YJW0TY7miFWrQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
