# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ows/p6kC++OX6eWsaF+LTbiEGz812sm3DsdmkddtO2MITWR4DYwmEw==,iv:hRONaEL/ND5XpAPKbCPukfX/XivrWCF7m3zu+yR3+1U=,tag:Jeuw6cvr5c3nISLo7jHjaA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUFFlemR1RFA4VzJjT3NC
        RjVqaG1ydEwySWpHSXNCK2gwaFJTRzVQU0FVCkZ1bVpHa2xVNmUrVUpCM09pSGYy
        eHpHcjRERDRZTmc3WEl4OG5rNTZyTVEKLS0tIGtlcGJVUzRyOG9aTndqWldrSFpv
        Q0dsejVBeWRuTzNrNFo3NWVjSTFYMkEKKVNqaeXFVQOdP/tdKDVoY3tjUj8cmNVV
        j2LETrapMp3WHHbfoL2SGgMsM+q2+sMBpV3MA/CD7ctrRMZb+QqCOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-10T21:58:14Z"
  mac: ENC[AES256_GCM,data:lobfxK4svCP3yC1FaCUIdQsUVzWe0MUhDkkqSYMN7NzRZVD53tbNJNCnPWGnMK3U8wpi1jUHHRvf3Gsr6mWy2eynIxvcUal0kBfKY77sKWctsvq9WI45K8tyoQIwWExg3zpImmiX1rEZajW9rV0h6goxOPPI7rxpBNjB1pkwFzU=,iv:wVUACSTA+k0bO99Q7eOBEt6b6FHF2/Lfl/uXgQV9HmE=,tag:mVPpeAhfEZtSPT58e0UUsA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
