# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:wTBAKtaJ3LGSpeFzIFKxcda05SNveqsWCvjTUwa1/dAFt1PoWuHxlw==,iv:F7ApLlqlyughIPLw+XifbUC8qIi4/VEM1CZ6PGbZaQ4=,tag:fZgJhUUstRjj/DLeJcrncg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMkZlK1dMUlZ5b0V5c0Jk
        aitKQkJnWGtieVF0SFdYd2FmQk9zZjJRQkRBCkJWTXVuMWhNTkRoR3VVSTMrbFdz
        ZWM0b29sK3pSN21ONWNKeFZJQ25qcEEKLS0tIHBrd3dKdFlTV1NJOUdoN3BTS01x
        NGM0akNiZVVSbkpsenFTaVBtWGNzWncK0bC3VagAwF30tWtso7tKDsyDhoeRbz6T
        XgsrPa439FjI4kocH4BTbc1UDISwq7M6/C5/JHxuxTSjNgkyOVpexQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T10:32:15Z"
  mac: ENC[AES256_GCM,data:Z728Kh0u9CcGTPo+aC61sbZdZ9GJskwU0OKZ6P746QEPFblFOLuyeXTWVeVZE6F2qAh88ByaxJabyE5ZnuidMKYz8nmmBnsTtkX840x5u59z0VbJWH5VnHeqosXclXWxF6kOMYREgk0vP4Js5FRiqVq/XTcyEFA1vK+KWwxVpDM=,iv:kWGroxa0gpe97Z9g7SZhSPdXP0BqI/szc1xZzh9L5VY=,tag:n5ipy1dY3tL49a7UqMr43w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
