# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:j3tVy3pJ4//GeC1LfsL/NR0mbUbtImKkfQqRj5bJF+nJsJSaBRJNwA==,iv:sgkEM+LvZi1iv7IxVQ/7aO7e6ra0YkQK7JgDdj1FtLc=,tag:kaw//gO/XecU8fEBor0N5w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYemNwZld4emdRZ0RqRnRp
        OFh6VXhvVXBpTjhBWmNaekZiTTJESkxVb25FCnFONmlMNkZJVFRLalVuVlQzcmQ2
        TVlmUng2V0RiLzlnLytrZVdPSEhHaW8KLS0tIDMrYmVsOUpmNnprYU12eGpJL2da
        MzVCWjQyU0FTK3pmeUFDUmpmclJQdDAKcrOw41m0MjXrz+jf02OSvRuyHt4q3jye
        pIllQDOnxGETW0PADLaxTaBpqZf1W4xb/aTzzsTSpYw8hDkTH9Fblw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-16T14:19:11Z"
  mac: ENC[AES256_GCM,data:evIsdsUZzy7hz8reF+W/O5pqrLsI4EMygcwF24ar9Hp5s2wbMl6PDCRKUgpd8GBRK8Mxu0JByu4lUqQdug5IKvwZelznS5dIoKKRQbsRa2UHcQTwlOZpqIJ5p2S2dL9puRWhVNErXEQh6xlxNQ4MP+LLugLivOeHNfkAvwPv9W8=,iv:UTDp2g76j3xPm6x4dnTjKqCybpTLPmI2+bnBiVqHQFo=,tag:+kvHfLbnsvNUt2G2ea+SLA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
