# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DdSJdpf2ESyCFpfpG1JK9gDpVI/gu87qZozXuEKDP9GzLTrKfDqZ5A==,iv:CNd1QbS6qseuwFidkFT6e6kkWQ0FKuCPYguIZyUnGTk=,tag:6bOmwu4r/3CxP0z5rYU53g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVmtxd1NRaGZ2aWVQU2sx
        QWk1bFNIRWhmOHhZaXpiMTJtenRUZy9HcXhRCnJZU3ZoNE1BN2hWUUJ5WUN4dzIw
        U1BIUDRNMndrUHZlMFdRZzhxbkc3dTAKLS0tIEphQkFQTFZkOHkxUHBkZkFPTEIw
        RDZ6V2FERStZRThURFlpRTNzdlNvTmcKMp1MzRjpe3IaZMiKh/UXhO/F9vLx+Cqq
        +TMT7BSftHrJDRgo/oOrGna7wLt6W12paRiUZ8MpOj+W5XOnRPbYvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-04T20:05:27Z"
  mac: ENC[AES256_GCM,data:RxdGoGI9KRTbv73THb5bndd60ZbNHxCejadvxrgV3gCuRzRSjQT3HOHCIHcLH1r6tf8887QewP8+DpcJxJN4eu1CyatFrZJhEiYZnQUJa8wI5KJYW5HHppjf9mdYSBdCpzvUx5f2/JHX6SW3KeZ1hXB6mzIUOBSYzOxdxCYtxrk=,iv:AdYdfwMWIUbtw2HxLVpAgMVHOe8YZ/ONvkDCHyf1A+Q=,tag:c2NUVHPimcyH/C/Igk+GiQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
