apiVersion: v1
kind: Secret
metadata:
    name: cnpg-su-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:jCgFQhMpjn0=,iv:b0HnYWE7r9M7SGQs+2XlxmfE2Q5stH+4GVH/IIIfI1Q=,tag:frTDtbz+boiV7tppOqHNWA==,type:str]
    password: ENC[AES256_GCM,data:SjqxwEkHSEU0+F6Z1g6rdCbotNuVtWl+OmYPsNf0hFiI3bSqDq9324VhBdvaeEu2WQSKs2k=,iv:FaTg1XebIFGT/AFqtlms9XnRf+WzNPqMwvay2+6ECY8=,tag:YNUesmsOKnRv6rsZ5jiaqg==,type:str]
    accessKey: ENC[AES256_GCM,data:AZwUOSv4Us8d2OvE+cPNe7kKu6YIjurIuwkcYQ==,iv:+s4dUSkQ2cdxtvshUQUW4NvFlLivX64BbTJdzbkA+HA=,tag:KxwSVysw5pmzljD29+UKaQ==,type:str]
    secretKey: ENC[AES256_GCM,data:MVrzcE2BIgXghfgKXqHrFwGu3FdnP0Mk8JoRgjgm/KM+Rv6aQd36kymonDER8myGp9ghUrA=,iv:/bhyiS5O581iCdcRbEsqiqJ8awWjxuW8feOzLJdLdNw=,tag:kUFjkFuT013SwRFLXIJzUg==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUWQrYm1iNm1DcFZzc2Vx
            TmpLK1FwVmZiTTFkTUdkejlQTzlCZ3F3dFg4CmJ1NXZwa05mMlloSkcya1ozN3pL
            S3puejF1aWc1NzlRU29wZ3REWUUyUFEKLS0tIGhpaFhEMUtOQnI1RVZxVDhUK3Nr
            UlV2eldOQkFsWmhuYzB6R0tMdzB4dW8KPsY6xIYJDFtpDcsZj9N1oRO8tcAW7jOL
            Jk3RI7GkV/VzW9fkzRZetrHTPW6njBJiUWTkM4FUzI5CQtI3VGGJAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-01T13:44:57Z"
    mac: ENC[AES256_GCM,data:1pHmA7WDEW69PBNkODnuyK1TqTx6D2TT5Qr7R9BNFQD6Zrxcpk30Y0lAS9SMRP+W25aXlov6wJPSioNkdstINcXgQ9MwjlegVcdsZQgPXh4jgEoYo/VqhgwoRo7McCqa93H/U+EHUZufO+CWHVl4O7n82k5h3jh/8pneZ7NVlXQ=,iv:49K1hQJ8JYFL5gvBUo0IpkvpnNU7L8/i3Gft9bDPyHk=,tag:jdqL5cxgx83PGUNA5UC73Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
