apiVersion: v1
kind: Secret
metadata:
    name: authelia-secret-db
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:6Eln1Mwa+3U25Gzucw==,iv:DRgYqZ43fk6JYfjAN+TtvAyFlTk3VxvnjTzZ22UDgMs=,tag:+kf+TQICKojFSWA0n64Y+Q==,type:str]
    password: ENC[AES256_GCM,data:k8jaFXnjYqvTigxcAJWfGha4g/fJ+yLgNe99C+lFd3rChY7ZABHGKRyf4VImiIw=,iv:nL1tPF8Vzu6GfhW2euQYv76tYsFP3I2JbSPVK45cqpA=,tag:uNqJUYyPj8viZV6Asz7SaA==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T18:11:16Z"
    mac: ENC[AES256_GCM,data:6KzDl/yjCTwyVzLeabaoJrLJ9f1Dsa3XC1MrBwwYI1SUDSSzSZ6v/H2pD3DtHd9Y47D3fm7rkTi4mREhf9GEiTn5KNgPOD2ui6sM5b8L0sdgYQBMPoCBbSDkFqXjwPcU8jcxaR08FRusgEAV8jb8GiWsA1+RZ+/YV+yjNsj4G8I=,iv:F9PrNOW0hTbgAEE4Pt/sTKxHTE5ODdqsb3IvcmZPzB0=,tag:tzXzxZ7UZFcowHk1PqN07Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
