apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret-db
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:LxmOfEk=,iv:xeE2202LGqMGLT3HHZ3U62eKqzlJ1OxU9nzI34cxoHI=,tag:D5eYCv/VD2hLR/E7ykjepg==,type:str]
    password: ENC[AES256_GCM,data:Zjuq0W7XoW65o3am+zrRi8ZYOycV7ronIYdplfGRx6bnCHqRuZU8RcEqC9G64q40,iv:x60Xzwso+zqdI2yG63udH08SaGrKVd/dX4G6KYopfiI=,tag:9n/6JGjJjJZwtrmGj4i3/Q==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T16:15:24Z"
    mac: ENC[AES256_GCM,data:tb0dKnI3toHT2Zkz6bQjL5kjfMcFfAEzd1dRoPa5l3y98frGn4lgqlw/9n+jJ7BnEU+wfVLBo2S/uws+TUS/xbhG+B09M11lhIPSRGAuV+pM8f6oNYEwlhE9CzIIixrXr5cQ0s+ZqJt5z1MIFURROLU8feteUF4+dQAuZ4WG6Z8=,iv:Vns7eN5UXOyuK0oKCGkhP3QIRFd7I4bguRSSW3f5rAo=,tag:vPbe0zuDJlIHuM5DRYoQFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
