apiVersion: v1
kind: Secret
metadata:
    name: cnpg-su-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:p3WL8L5ZZCU=,iv:uEgxOiSp6jNM5Ar8ZCGFEAAtprnKEf28dnl9G9J6IL0=,tag:9x6nKG346iw7naXzME8JqQ==,type:str]
    password: ENC[AES256_GCM,data:/sm5xWfU3K+mk37so3fPwIONRqunbqqiZQlvB8Xf9ZNErbixJzV/nfxDHKejtWpc2EyOgdjj,iv:pr3hoGHbUn7t3PUU+/OF7V5+Ff9AA8EGnWBOwJsSgPs=,tag:cH47S/01Fhgj48Q1nZ/wZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T17:50:11Z"
    mac: ENC[AES256_GCM,data:P6+UdF8XIYjh/YSUREfal0+E+1orkxtu7OkEypNsLACfb/eO5cwqd5+6Tsaodo1C+OPM5fCyos7tHEmpz452ewyVmg3QNXWDmGgQyr8Igre6OcS+x62k+uZtmXE/TeUw09BeURG+eKD9d9sOglFepdWk2N8D7mdGT2nsKyoWbW8=,iv:OvHumvMN/JK6/OhO+5b/W0jPdFSbrhEwrDnJnYMQZyo=,tag:7PfumV0ClkJZL59cy/Ll1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:8S6RxliJlvWW,iv:wTlwTXzIpU7X4r14Ogz6Yp9wr2ZoT6KyfprCX9wKpjQ=,tag:M2vsMbkZWb11Pm7zPZ3Sdg==,type:str]
    password: ENC[AES256_GCM,data:Dt3dgVmSsF3/2F3ir6jc+g4S2MtVk3LKO3vo3Ktx+QQbjOTjVWlA2Co2X+amuUUk8w==,iv:dG64PIeXMC6aAbGT/I+t5h2/AW9fKomfxZf3uyPBi+0=,tag:JCejrDOVt6SLjkvaKE0mUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T17:50:11Z"
    mac: ENC[AES256_GCM,data:P6+UdF8XIYjh/YSUREfal0+E+1orkxtu7OkEypNsLACfb/eO5cwqd5+6Tsaodo1C+OPM5fCyos7tHEmpz452ewyVmg3QNXWDmGgQyr8Igre6OcS+x62k+uZtmXE/TeUw09BeURG+eKD9d9sOglFepdWk2N8D7mdGT2nsKyoWbW8=,iv:OvHumvMN/JK6/OhO+5b/W0jPdFSbrhEwrDnJnYMQZyo=,tag:7PfumV0ClkJZL59cy/Ll1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
