apiVersion: v1
kind: Secret
metadata:
    name: cnpg-su-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:p3WL8L5ZZCU=,iv:uEgxOiSp6jNM5Ar8ZCGFEAAtprnKEf28dnl9G9J6IL0=,tag:9x6nKG346iw7naXzME8JqQ==,type:str]
    password: ENC[AES256_GCM,data:lIQCF324t9IT8ZdUG+CC38dN2u29TN2b6mI5rB+WfBBR+jiwGaDKJ9RTbyfvWbzRgO9YdCg=,iv:vzgsP1FLxS8yg4Lsa4A/cmkMKLwEscg/ndDocxG7G8w=,tag:Up1wcdqETbBW+v+1EED0Aw==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T15:04:29Z"
    mac: ENC[AES256_GCM,data:S2qVS5qizGWUiSOHm7O+0WLEm7eNQcmTgrKkZcj7CGLSeuBKZGUCNG0NsdXQGf/i6LT+Cp7gw3/MsPLEhvoYEmEbPLUe9ek8FrXma3OROzF+0Lg4fbtX6hpsXftLdaBMgbe97wp7nTcST3Ak5GlSXydsEQsBv7vHEQ/d70r6GbE=,iv:b9CriBISjWbGB84bbbzGtgt52OTa/96pv04c315v2/w=,tag:b6yESsl/5xlMYmNbYmkw+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:8S6RxliJlvWW,iv:wTlwTXzIpU7X4r14Ogz6Yp9wr2ZoT6KyfprCX9wKpjQ=,tag:M2vsMbkZWb11Pm7zPZ3Sdg==,type:str]
    password: ENC[AES256_GCM,data:Zjuq0W7XoW65o3am+zrRi8ZYOycV7ronIYdplfGRx6bnCHqRuZU8RcEqC9G64q40,iv:x60Xzwso+zqdI2yG63udH08SaGrKVd/dX4G6KYopfiI=,tag:9n/6JGjJjJZwtrmGj4i3/Q==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T15:04:29Z"
    mac: ENC[AES256_GCM,data:S2qVS5qizGWUiSOHm7O+0WLEm7eNQcmTgrKkZcj7CGLSeuBKZGUCNG0NsdXQGf/i6LT+Cp7gw3/MsPLEhvoYEmEbPLUe9ek8FrXma3OROzF+0Lg4fbtX6hpsXftLdaBMgbe97wp7nTcST3Ak5GlSXydsEQsBv7vHEQ/d70r6GbE=,iv:b9CriBISjWbGB84bbbzGtgt52OTa/96pv04c315v2/w=,tag:b6yESsl/5xlMYmNbYmkw+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
