---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: &app cnpg-authentik
  namespace: databases
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-4
  primaryUpdateStrategy: unsupervised
  storage:
    size: 1Gi
    storageClass: local-hostpath
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    nodeSelector:
      openebs.io/storage: "true"
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 2Gi
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  superuserSecret:
    name: cnpg-su-secret
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-secret-db
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg/
      endpointURL: hhttps://gateway.storjshare.io
      serverName: *app
      s3Credentials:
        accessKeyId:
          name: cnpg-su-secret
          key: accessKey
        secretAccessKey:
          name: cnpg-su-secret
          key: secretKey
