apiVersion: v1
kind: Secret
metadata:
    name: cnpg-su-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: auth
stringData:
    username: ENC[AES256_GCM,data:p3WL8L5ZZCU=,iv:uEgxOiSp6jNM5Ar8ZCGFEAAtprnKEf28dnl9G9J6IL0=,tag:9x6nKG346iw7naXzME8JqQ==,type:str]
    password: ENC[AES256_GCM,data:/sm5xWfU3K+mk37so3fPwIONRqunbqqiZQlvB8Xf9ZNErbixJzV/nfxDHKejtWpc2EyOgdjj,iv:pr3hoGHbUn7t3PUU+/OF7V5+Ff9AA8EGnWBOwJsSgPs=,tag:cH47S/01Fhgj48Q1nZ/wZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T21:06:50Z"
    mac: ENC[AES256_GCM,data:nBYHffd2JwG7s4bFbqRxp0zt4fl22mHoXNSD0WLnNh3j1cq+bDkHVf0JIxX3OSeFdCKsyim8mOayTYW2UiT3e6sxtV/rGmdbXvuIjRXHBR1O9Iv+fmGIHgMo3bRvZNnaJru7VCAxuJ1hJFUmMCEAsDLkIGtOurvUggZEE1yJAGM=,iv:VAEv1/PB1fwad/duxIr7mZ8dV1CYb5RoGbM3GWQPYRY=,tag:DvlQdR2nR5h9H4h2XfnHpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-authentik-app
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:wqfVz0nExsNyMo8=,iv:G+42bdzuXh/Ff0A5FXLzuwoPLv0BuvYTTtxtgSHbh+o=,tag:pWHmL7o+E0NbXyCre4wYHA==,type:str]
    password: ENC[AES256_GCM,data:ktjI8KGs0mhoPIgOuk+/ynrWopIaSahn+JVWcYtmpbr9T14QJMHM2DDtluK9GvMtW7iY,iv:KeUaKxM2lE6zL1iFRBRQITjn6mMz70c1dByvUBXQUq0=,tag:SIptT8s1mMyf8dSO6zG88g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T21:06:50Z"
    mac: ENC[AES256_GCM,data:nBYHffd2JwG7s4bFbqRxp0zt4fl22mHoXNSD0WLnNh3j1cq+bDkHVf0JIxX3OSeFdCKsyim8mOayTYW2UiT3e6sxtV/rGmdbXvuIjRXHBR1O9Iv+fmGIHgMo3bRvZNnaJru7VCAxuJ1hJFUmMCEAsDLkIGtOurvUggZEE1yJAGM=,iv:VAEv1/PB1fwad/duxIr7mZ8dV1CYb5RoGbM3GWQPYRY=,tag:DvlQdR2nR5h9H4h2XfnHpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
