apiVersion: v1
kind: Secret
metadata:
    name: cnpg-su-secret
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:T7is+yeLuA==,iv:BBBEDIq65h/GbfAqy/xw3MvfBGmHJiJ9Xppg+AsfKqw=,tag:J9DKuUtRvQEL3N2XBMcV5A==,type:str]
    password: ENC[AES256_GCM,data:BsGVhlGnbYkfbGx9qltQl8hgyb8bBNZv8eI=,iv:bd798UJGt+EXkE39TR85DsK9B5JZFKZWbzMGzJOZVHo=,tag:d7pB4w7AnvSaPNBCQLjS5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUjlSMUlMeFlwb1I4WWQw
            dms3Z3d1ajNHNWVRNFlvUHlrZzZWR05qbWpZCkRkR2VGMTVpYXcvclVEbE5VbWhF
            L2o1SGliemtiaXA2TVRSajJNdmRSK1UKLS0tIDZLb0d6UG51a2M0OFptTC9HMkxm
            aEE4ajdseFYzU0ZCL2FYdHNJaFFCbm8KCikYc8T4zUz0Khqlxm/VTZ+DztTau7e4
            cSuqfD9xLn4/+6WzUmicLhXrdyMAUbI4Gs79YCZsQs2LSbNwBJkq7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T19:36:34Z"
    mac: ENC[AES256_GCM,data:fD7pz1buxpHA/yvgSBYWL6hzmXJLpsELkhE+9E0YU/Frv5CLRn7D5ehXPT1qKk+b5/pDWRABiI9pYhnKhlOcoygOMI11RWa8AQL9BztU/PYKCviPDIXmfUZRflngWKpxY3ZrZcaOTVSosvXqdXydU3dexyxKw/qSVly57IlG6aA=,iv:qW2HnJcgZXxdCSHsE9o5bn09JdnA8lgv54G1x1qUJ3g=,tag:sTJSSuAwkUbX4G+rHYkfDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-authentik-appuser-secret
    namespace: databases
stringData:
    username: ENC[AES256_GCM,data:T7IKzoecQf7QmL0=,iv:yKeXmJMYdLbyNUwbOAfib2j/rEV4fACrUbPZ4GLzlJ4=,tag:OkAxaLI+QKPJtVPpKeLMBQ==,type:str]
    password: ENC[AES256_GCM,data:E1pQ2/p4taE9SWuVLIyrd/kcMwrwHq6Q9lkRe6CD1eWauINtPb56,iv:eySE9w6o3rT05jDrZfSzaceHQbjQefxY3FJzBAFfLCk=,tag:qtrChCZz7Jw81x1TqVmRaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUjlSMUlMeFlwb1I4WWQw
            dms3Z3d1ajNHNWVRNFlvUHlrZzZWR05qbWpZCkRkR2VGMTVpYXcvclVEbE5VbWhF
            L2o1SGliemtiaXA2TVRSajJNdmRSK1UKLS0tIDZLb0d6UG51a2M0OFptTC9HMkxm
            aEE4ajdseFYzU0ZCL2FYdHNJaFFCbm8KCikYc8T4zUz0Khqlxm/VTZ+DztTau7e4
            cSuqfD9xLn4/+6WzUmicLhXrdyMAUbI4Gs79YCZsQs2LSbNwBJkq7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-10T19:36:34Z"
    mac: ENC[AES256_GCM,data:fD7pz1buxpHA/yvgSBYWL6hzmXJLpsELkhE+9E0YU/Frv5CLRn7D5ehXPT1qKk+b5/pDWRABiI9pYhnKhlOcoygOMI11RWa8AQL9BztU/PYKCviPDIXmfUZRflngWKpxY3ZrZcaOTVSosvXqdXydU3dexyxKw/qSVly57IlG6aA=,iv:qW2HnJcgZXxdCSHsE9o5bn09JdnA8lgv54G1x1qUJ3g=,tag:sTJSSuAwkUbX4G+rHYkfDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
