apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-db
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:8S6RxliJlvWW,iv:wTlwTXzIpU7X4r14Ogz6Yp9wr2ZoT6KyfprCX9wKpjQ=,tag:M2vsMbkZWb11Pm7zPZ3Sdg==,type:str]
    password: ENC[AES256_GCM,data:Zjuq0W7XoW65o3am+zrRi8ZYOycV7ronIYdplfGRx6bnCHqRuZU8RcEqC9G64q40,iv:x60Xzwso+zqdI2yG63udH08SaGrKVd/dX4G6KYopfiI=,tag:9n/6JGjJjJZwtrmGj4i3/Q==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bDMvUHNnZ3VtSEFKUkZu
            TWdhQ0FrcHZBQWEwNDRJWkIzcTAvMkwxTjNrClVvRUM5RG9QN1kwdHZ1Z00vRHNy
            alFvWmQrQ0ZuRWJvQldMekt0Sm1RTEEKLS0tIDd3R1g3Tk1tUjZ4UXgvR1QyRmxi
            eFNXUXg2cXdSZXFpajZPdDJrRitZb0UK2cjrpEJmUFGy/RVtiK7uN4sdSsFX88un
            YMqEeOn1SB4SrtW3s9JueuX68LoXJng+HGWmysvikVQD2rdBinaGhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-01T11:12:36Z"
    mac: ENC[AES256_GCM,data:a2voYfjhbG2w86UFULVcYPSeSL1IQh2RL6ADUxlPyzdumyf+JhTwmzvk79A6LHn+ybmjMRxsCtnZzgNwLE8Nat8ysEuSt+Auc/xqAt0f2nEJaIZntjkC56otAY5h3YqXtOYqF5H6UmQSP2bcu5mhJvRzh008Ja1yYqF4xZe18RY=,iv:Rfls+MJp17yNBhsOWqhbkGGheHfJ6/uTh3VrVaZEX5g=,tag:vmY54ys8PgT2hIsrR2G0QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
