apiVersion: v1
kind: Secret
metadata:
    name: cnpg-su-secret
    namespace: databases
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: security
        reloader.stakater.com/match: "true"
stringData:
    username: ENC[AES256_GCM,data:aLt/F7sz10ulan/7nA==,iv:3SAQCw6vRrpsCYWmGCHxruDRDkxlvBAGOiplYo1TmR8=,tag:bXpUZR+rnP+puTMc6ZJUbA==,type:str]
    password: ENC[AES256_GCM,data:/0Mt50Mtq7KqhZwIbKYPu9U=,iv:9Cu36cP5+IcoePscvUoiiJY9hU0SYMGPEhgO3LqDFGI=,tag:9IgD0Many4C9Fl26w2nkDA==,type:str]
    accessKey: ENC[AES256_GCM,data:AZwUOSv4Us8d2OvE+cPNe7kKu6YIjurIuwkcYQ==,iv:+s4dUSkQ2cdxtvshUQUW4NvFlLivX64BbTJdzbkA+HA=,tag:KxwSVysw5pmzljD29+UKaQ==,type:str]
    secretKey: ENC[AES256_GCM,data:MVrzcE2BIgXghfgKXqHrFwGu3FdnP0Mk8JoRgjgm/KM+Rv6aQd36kymonDER8myGp9ghUrA=,iv:/bhyiS5O581iCdcRbEsqiqJ8awWjxuW8feOzLJdLdNw=,tag:kUFjkFuT013SwRFLXIJzUg==,type:str]
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUWQrYm1iNm1DcFZzc2Vx
            TmpLK1FwVmZiTTFkTUdkejlQTzlCZ3F3dFg4CmJ1NXZwa05mMlloSkcya1ozN3pL
            S3puejF1aWc1NzlRU29wZ3REWUUyUFEKLS0tIGhpaFhEMUtOQnI1RVZxVDhUK3Nr
            UlV2eldOQkFsWmhuYzB6R0tMdzB4dW8KPsY6xIYJDFtpDcsZj9N1oRO8tcAW7jOL
            Jk3RI7GkV/VzW9fkzRZetrHTPW6njBJiUWTkM4FUzI5CQtI3VGGJAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T22:24:48Z"
    mac: ENC[AES256_GCM,data:oVZZMetFYDKnIq4TOf8kxNbeaZyFKdGvtgTL7tDYA90VIANH1/ML59IJVNq6dJ7xiPLW5VECBu019agFpOyv+Tz/zIg+cQ/8cb4URWGHJdYUHauiS5Rew6/IPEiIpbw4uv4vM5BFRKe2UJX6BkBqBL01gMH4oLIBt/rR+gZcXVI=,iv:FoU9jtu1S/k4PJTDJ/Hpr+R87Ph3AxSVwKXONGJrP8A=,tag:8ODCxNidaI5TgYrmSX/ZSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
