apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-superuser-es
  namespace: &namespace databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: pg-su-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Postgres Init
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        AWS_ACCESS_KEY: "{{ .AWS_ACCESS_KEY }}"
        AWS_SECRET_KEY: "{{ .AWS_SECRET_KEY }}"
        AWS_BUCKET_NAME: "{{ .AWS_BUCKET_NAME }}"
  dataFrom:
    - find:
        path: POSTGRES_SUPER_
    - find:
        path: AWS_
