apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:mo+2vZ5aMs55CWWNVtKzZeJ3OLhV0RsSzsFoVARCY5DbfuHK+7HO/xb9Nuq5nHQbO+NAunNo9TTa1O55n2WuG+FpR79Ef74S779kadwdPp+ze3eJC5TzcUbT4zrRwQ==,iv:hj+c7JbfncDPOxZblqgorL+STc2QLaRCVYCRnP5tM8s=,tag:gSxx8JxUPW4kAAk9tkbctA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:eVBfyTM0EKmSEpHiirbO,iv:UkkxjzujBqXovQIUz1u7yYFM2/UtekFsk94aax6crDs=,tag:wLq5KebPJPtkEhCm/qDFoQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:EdmdrpRefbLlAyOXHflpbRXu,iv:U+2eCantw3XVbNLucOt+dMwhNddFsVuJGSNdzWmSoo0=,tag:lPctVCLZvrom95s+iDy1lw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ZzOrpuV4qU+Ph7EvVzlR3VsWjx9PFMZriIRsjWhal6kQDGCP,iv:gyAMiIVV26T+yVHM3heotlofWgefe6zuaGECp215QD4=,tag:z1nwGm6RjHSs8iH1UQZD1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBROC9rNjNqQXBLOU5YN2xQ
            WVZ2ZWhBQUZqTFc1NENBeE1JUzZ4Sk5XbndRCnFJQ3JLS0FRN0NsMjBDblB6Mmt2
            QW43ek1hRHp1ZVlIZDQyUC9XS096ODAKLS0tIGxyZ0g4bjMzMVFhbUVqdHo3N2Qx
            WEdRVjRIakprcnFNckt4Z1M3ZXQ0UTQKozQZyTTPMBwh+Dka1ZVOYH6MsdJHx3Tj
            OVYKwY0jmzcBhip5v9aqX24mCwhTJYenZXoVm/E3jvFoyo4DnFxQ4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-15T20:05:16Z"
    mac: ENC[AES256_GCM,data:rQgFO3a1rOb1SAG1T92HFL5l0od+odqjAcd3CHlpAu/Ay05aPFmL4v3H1H3JbHOesrWEPZZZIvoGQd8YS7z3ZaZyjaOO0wwpslN4lMCWk0jcetinj/oIg+Eftk2CYfrWj76483w26EG9dLo2/x+EWV4e7PIclVcpUyzU36rL4ck=,iv:UnKxgg5mI9CkScPW9eskZENkeIx5GH81h04S//9uAfA=,tag:CpbUz3c3sMI/vxHztKlZKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
