apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:TeZPfrvV9KxiDERQ,iv:O+wtaUXQSr2UMB1TitrJCoao1w17SAZ/dXrhE0lyMTQ=,tag:2sf7x0TVWGa9/rbwShnocw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbTJ6dTRLLzY2TnFCT2JK
            UGlnanJmS21rOFZScXk1YmVHOU5wUXlSa1VFCkxaS1h4ZmM5UEFMVjhkNjdGNVZD
            QjhlY21mMzdLU1RXR3FHUmFnL0dzVjAKLS0tIEpXNDkxL3M2Z3ZqaXVlOE52MUU5
            andqcnU2RWJJd0dUQmU1aFA0U2VOV0EKe9pD2W5rY0Pm3aFqLWnbzw6XN4Bu4M/A
            YVMGFGs0h6iBxwo3cA6pAHJmctdw4BGeFs9RiSEs3o5A8ufxZx5kZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-01T19:26:39Z"
    mac: ENC[AES256_GCM,data:WT9i+GpWKD252T+xnlkiUykJfCUs280j4LMDgyk9yFbTf+av2vMxKCqD1AQSI0tpHywP44QdguISmIHulzWmI7b9PxblyLrg3N9iaA07LNYTM7WFmCg3pd1+atr/Z7xeHZqYenokeMvVUYjGuxQy2Is/qdFARZwPW/VW1scXlmA=,iv:0MEfda/NS3aW/0KgVLcuaTjUMATVJGYcEZnqHl16lZo=,tag:AYmZsenAXVcCNFNMqQ6uRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
