---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: storage
spec:
  interval: 12h
  maxHistory: 3
  chart:
    spec:
      chart: tenant
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
    replace: true
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    existingSecret:
      name: minio-root
    tenant:
      name: backups
      configuration:
        name: minio-root
      buckets:
        - name: backups-authentik
      pools:
        - name: pool
          servers: 1
          volumesPerServer: 4
          size: 1Gi
          storageClassName: local-hostpath
          nodeSelector:
            openebs.io/storage: "true"
      users:
        - name: minio-users
    ingress:
      console:
        enabled: true
        ingressClassName: "internal"
        host: minio-console.${SECRET_DOMAIN}
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - minio-console.${SECRET_DOMAIN}-tls
