apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: storage
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:W40/hDKYStxr/5lPZSBxos3p2a8wJjo08i8C7/qAHy9hMxKy3YWb8ZqIvAHMSyWmhddHY8ABw0WRlQZb4l+45l6EQkvT9Skhx2C2hzCuILX6B96xvKKiCi6aP54X4YjSX3fIYFsl0gRk3L50RldvcS4YBobMnFSPeUkNQadxstpQ6bQ4QBzqerbH5eLcSCrfMkpvVnm/YGfSV2i37lV5X/wD+nVfzu6J7eZbhicxPS+FL3T/OOCnqiju+JEzmAaEldLyZmSFVAYGUlajCkRdZxk8vPW/KHkAFuM3fUh86YuvaQx1HTSP,iv:10Kwc4o/C2eZukHOwWlcqwvK6qxw/4lrganjgKE6r2I=,tag:c/fbnHG5zxGWAOoECyudeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRnIwUTI5aVdkOUhtQmxn
            MU1LVzRqb3U1cFN1aUdNUzA3MHVVamNCZUhnCjQzc1dxc2V2eklnMjY2U2VOeFVv
            L0h0YXlZcC9TUUNhMkIwWHRPdTFBUE0KLS0tIHpaQ0dBS0V3U2dkNVEwRURvSlVN
            ZGhmaFRqeG0zVmkxcEZBL2pwci9LK1EKPv5ylxL62MtSdM7qZNlq/7v20tlVWBOL
            /GRJOLg6eonEpV/YHkXFYSaohuaSMnv7FvkEQJkgr2jVjQKPf9rp+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T19:33:30Z"
    mac: ENC[AES256_GCM,data:5X6u2uJvglgy9r7LR1Lyeb14FDSmhQOxmBqtX4L6EBpiIFclzne1Is0gVlNoDJIkLB91zmAnMy6Bt+QJh2UQGSEsDPcDuROsvTRmlhfIaKrivZfRdeOq0WYBvaJ98QpKJMSqUwtKzrfJL3u/bSvJs2A5N98NmO9jfpwiksvzjMo=,iv:iHWPNVwYVuJQh81oytAw9srVRjcvHxEmdfDV6bfsuxs=,tag:5qdlhX2UVcIQ6UYzibPtPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
