# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
# renovate: datasource=github-releases depName=siderolabs/talos
talosVersion: v1.6.1
# renovate: datasource=github-releases depName=kubernetes/kubernetes extractVersion=^v(?<version>.*)$
kubernetesVersion: 1.29.1

clusterName: &cluster home-kubernetes

endpoint: https://10.17.8.98:6443

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

additionalApiServerCertSans: &sans
  - "10.17.8.98"
  - 127.0.0.1 #KubePrism

additionalMachineCertSans: *sans

cniConfig:
  name: none

nodes:
  - hostname: "k8s2"
    ipAddress: "10.17.8.12"
    installDiskSelector:
      serial: ""
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "10.17.8.1"
        vip:
          ip: "10.17.8.98"
  - hostname: "k8s3"
    ipAddress: "10.17.8.13"
    installDiskSelector:
      serial: ""
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "10.17.8.1"
        vip:
          ip: "10.17.8.98"
  - hostname: "k8s1"
    ipAddress: "10.17.8.11"
    installDiskSelector:
      serial: ""
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: false
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "10.17.8.1"
        vip:
          ip: "10.17.8.98"
  - hostname: "k8s4"
    ipAddress: "10.17.8.24"
    installDiskSelector:
      serial: ""
    controlPlane: false
    networkInterfaces:
      - interface: eth0
        dhcp: false
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "10.17.8.1"
  - hostname: "k8s5"
    ipAddress: "10.17.8.25"
    installDiskSelector:
      serial: ""
    controlPlane: false
    networkInterfaces:
      - interface: eth0
        dhcp: false
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "10.17.8.1"
  - hostname: "k8s6"
    ipAddress: "10.17.8.26"
    installDiskSelector:
      serial: ""
    controlPlane: false
    networkInterfaces:
      - interface: eth0
        dhcp: false
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: "10.17.8.1"

controlPlane:
  patches:
    # Configure containerd
    - &containerdPatch |-
      machine:
        files:
          - op: create
            path: /etc/cri/conf.d/20-customization.part
            content: |-
              [plugins."io.containerd.grpc.v1.cri"]
                enable_unprivileged_ports = true
                enable_unprivileged_icmp = true
              [plugins."io.containerd.grpc.v1.cri".containerd]
                discard_unpacked_layers = false
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                discard_unpacked_layers = false

    # Disable search domain everywhere
    - &disableSearchDomainPatch |-
      machine:
        network:
          disableSearchDomain: true

    # Enable cluster discovery
    - &discoveryPatch |-
      cluster:
        discovery:
          registries:
            kubernetes:
              disabled: false
            service:
              disabled: false

    # Configure kubelet
    - &kubeletPatch |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: true
          nodeIP:
            validSubnets:
              - "10.17.8.0/24"

    # Enable KubePrism
    - &kubePrismPatch |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    # Force nameserver
    - &nameserverPatch |-
      machine:
        network:
          nameservers:
            - "10.17.8.1"

    # Configure NTP
    - &ntpPatch |-
      machine:
        time:
          disabled: false
          servers:
            - time.cloudflare.com

    # Custom sysctl settings
    - &sysctlPatch |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: 65536
          fs.inotify.max_user_watches: 524288
          fs.inotify.max_user_instances: 8192

    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true
        controllerManager:
          extraArgs:
            bind-address: 0.0.0.0
        proxy:
          disabled: true
        scheduler:
          extraArgs:
            bind-address: 0.0.0.0

    # ETCD configuration
    - |-
      cluster:
        etcd:
          extraArgs:
            listen-metrics-urls: http://0.0.0.0:2381
          advertisedSubnets:
            - "10.17.8.0/24"

    # Disable default API server admission plugins.
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-system

worker:
  patches:
    - *containerdPatch
    - *disableSearchDomainPatch
    - *discoveryPatch
    - *kubeletPatch
    - *kubePrismPatch
    - *nameserverPatch
    - *ntpPatch
    - *sysctlPatch
