---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.10.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
  values:
    initContainers:
      init-db:
        image: ghcr.io/onedr0p/postgres-init:14.9
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: authentik-secret
    annotations:
      secret.reloader.stakater.com/reload: authentik-secret
    authentik:
      log_level: info
      error_reporting:
        enable: false
        send_pii: false
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      redis:
        host: redis.databases.svc
    ingress:
      enabled: true
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: mdi:id-card
      ingressClassName: external
      hosts:
        - host: &host id.${SECRET_DOMAIN}
          paths:
            - path: /
      tls:
        - hosts:
            - *host
    envFrom:
      - secretRef:
          name: authentik-secret
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
    autoscaling:
      server:
        enabled: true
      worker:
        enabled: true
