---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app authentik
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.8.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
  values:
    # nodeSelector:
    #   openebs.io/storage: "true"
    # global:
    #   storageClass: openebs-jiva-default
    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik-secret
          key: SECRET_KEY
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: cnpg-su-secret
          key: username
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: cnpg-su-secret
          key: password
    replicas: 2
    annotations:
      secret.reloader.stakater.com/reload: authentik-secret
    authentik:
      log_level: info
      error_reporting:
        enable: false
        send_pii: false
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      postgresql:
        host: cnpg-authentik-rw.databases.svc
      redis:
        host: redis.databases.svc
    ingress:
      enabled: true
      ingressClassName: external
      hosts:
        - host: &host id.${SECRET_DOMAIN}
          paths:
            - path: /
      tls:
        - hosts:
            - *host
    postgresql:
      enabled: false
    redis:
      enabled: false
    geoip:
      enabled: false
