apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: auth
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ffCd9DGwEIqd,iv:+w04uE9IB0oQTRzeJxc3iVsXEjaN6bbV2pZDBbO4JHE=,tag:v+WzMwHon0iUhnZCl9f0Lg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:fu0128Wo2l5wswNprlq0UsjgYjt2T0W37xfFakEKlmATQg==,iv:PF2xrPaDvF9OpujY4bFQWslFAsTpCdMK0jY3pbk3zZc=,tag:5sIWHkICxVLl55EXFG6jxw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:7hF4HYzq7NPq,iv:+PrGw+LFcfbvbjl43jzF4eabZUgImu3sJJrvPLRWpRU=,tag:S4msi0Pa72RbDErSD5vujg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yH/oFGxZsRjWeAba5n0/qHp2eIxDxj0GUgQkIkMK5T1KXA==,iv:v2Ddch7jvIfu76qn2Xg9EWkzL0yvbuLA+i/KpyNKSBQ=,tag:uIokyPrFSOEpNXiKfikMLA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qi1K/SO41HcOiH07ZgpoO/FaXGtZCSR3QJH8AaXEpKiZDpGc83Y=,iv:scHntSMgX49xDZmrTxD3J93SVyL0Lcl9/BmT8jeNN8o=,tag:d2k5l9mj5GRCZlUdORBekQ==,type:str]
    #ENC[AES256_GCM,data:zyb1W7nfSiOVQe9kLlerVaZ/9L2Jxy1eMOkLzzWM6j1T7L8guwuMXzBINsjnSQGSl56RvwvUXthKE5cV/qaCcR8brnZl+GtvRUyKM4DBnQOH+ApEwAEUFTS9ObPTp6POvnPhdUGBZcFMrsDfH+vmDrOcWQ5g7BAEpq37A3C28A==,iv:UZv1nl6OMih9lGz8m4qUoi4IOF+JEnQf8T2aAkwjhyo=,tag:kVzUfcfyzIpL+tNV/kUQVA==,type:comment]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:SAIBBJdkePWZ,iv:EXz2u6nM9AtoVB6ri2gbR0F6WIATA4NAHz06XPwur4o=,tag:5RcG3N98Pirw9P3DYGN5KA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:JPhZxrzD0kPKzpCizZfjck6OeAq0x5plJy+nDPpelLCGGQ==,iv:Yyb4RUH2UrNHHEj+tiK6feVG2rECL+id0x2gKF+hERY=,tag:G7jRBexYRPmt1wZdi2XDbA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:CTYpGx7u/ESO,iv:2trxaa2zIbgPPn2v6UFBGD0DJ+E/ETZzZw38hHBtyhc=,tag:fTTOMhQ6uKDg0Tpb+n8K8A==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:76lDp/J2IVF42oKx8yQ5SEypGDxDKI9lkU67ifuhWT4Ifg==,iv:lth9GEo8H9T7+UNcK8racuxfhTqAMAQCPmVRi7X1/Ys=,tag:tUNAWHa7LNBU2N7Jwsa6Vg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:wrEp4x9uBTJGCWYdkI6T3ndfxgYuyJnyn9lFJ5T0Yh0TU2ecJYvHnTl2hbAWW4ma,iv:oGpY9eyyWTUspuAfx0ydF7V0WqD8ipBeDNRCb144TOQ=,tag:cT/A1mASj1AQZDmUq0hyxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTEE2SC9BbDRaQ0tTbmhF
            M2tNOFFCSy9LM1p6QU83YkRleE95TWd0VEdjClhsY09JVklxb05xN1MrOEVET0Mx
            NUNpY01jaTFhQi80RnNxQmEwY3JIZjAKLS0tIGI1Z1BOZ1dtWDNLQVFhTDJXV3Q2
            dFpoWGl2OTBqK2dWM3hhSmlINDlodmcKvMYOHLhvqeYBDMhTa6NfQxmV/n9/qBke
            Ty5i0Y22spBQ7xohWijdNth+n/QMsQ74TpQ5d7qQccMNfRnXKmLQaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-17T13:30:52Z"
    mac: ENC[AES256_GCM,data:t+AMnl75VSNeIa9H7TZr24jKQC1GEllmC7nvKNGaODLxEClLhKwW/s9Y8oWEv9OTuNrqFKLSLS5TP996Xb8DNcB3/jEYGyliTz4YmO1I+HRPNwNHoOHKndpfRgQhwIe5FWlkBXMt5edNfn1DekuZ4UrLquzjQ2oR3ztMdvELO60=,iv:FN00OAvr/zo+anJIHvl7lybkRQvscfzMWNSyW5fsjyQ=,tag:F+lwYO0zm/LB8PDFHs/YOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
