apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-external-secrets-operator
  namespace: security
spec:
  path: './kubernetes/apps/security/external-secrets/operator/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: external-secrets
      namespace: flux-system
  dependsOn:
    - name: cluster-apps-cert-manager
