---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app external-secrets-operator
  namespace: flux-system
spec:
  targetNamespace: &namespace security
  path: './kubernetes/apps/security/external-secrets/operator/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: *app
      namespace: *namespace
  dependsOn:
    - name: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: &app external-secrets-doppler
  namespace: flux-system
spec:
  targetNamespace: &namespace security
  path: './kubernetes/apps/security/external-secrets/doppler/'
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: doppler-token-auth-api
      namespace: *namespace
