apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:7S83RPVsL2+5ZJ/OAUvCAw3xJHCrmRfhBALqjZdY1/M3cz7u,iv:N7Mnbv5GyKHp/wYBVRANB3LibSEeNcpBcQGTisK22Hk=,tag:WbbxvY2/BVyrzSYOxzfPVg==,type:str]
    credentials.json: ENC[AES256_GCM,data:OW9sSUBBa8TDpAlcySYz3MK83A1XsJ1U61CS7bB4QL9rI/+tfyQj4g4ZuHgrrb+nBWElnK8nt9t0NbjQYRnbWRTMMai3/zmxDMuyaFyjwfmrgBGeJr6A2tyQQNIc1LXLUUtDdXbymlxMflKJpIffP9Yx+NXXb/lVcqARc+f/W8Rc322vQ/7fxrVr7ESIxJDo9wgo6RXXASng4M0eev6PdSIggN8NZVTLfx5M4jU+Lg==,iv:Nny49bQ4XPK06fbPSdm+4kJ9rMh2oIUyYiHW47ptHcI=,tag:4EsEPsM+d630/008h8EGhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VWptZ2sySlEyeDVzMXU5
            NXJwK1pHNkVwQ1NvY29CTW0xSEl5Y1BRNXhnCm04QnFPSzlUWVR1bjFuOTZwZ3R2
            Z0pZc09JM0U3VDEvSjRXcGQ2aEZMRkUKLS0tIHl1S0hRc2txSjlKMWZKc21vSFZv
            WDQ5VHplMnBhUGoxUEFGTXhRMEJ2UjAKtnMovQGHrThhQX8yLcV2LYlPGunf2wfH
            k75MZH0RhzadGgItw3EgzohA9+egSTXmqoc+NgRrbiYf1bl6j5d1gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T11:23:47Z"
    mac: ENC[AES256_GCM,data:FxKqUDKNZ17XPZVquOFpt8YoBNjM008YZFD8YEAtMHX48ZQQgDnbq1AXtcZepGZIKn7F5LKGMmAzdELBTK3xZQjHLQIKCz3SUnIsheqLnLGQ8P6+xEoMLQlpgJX+v1hja1qD6Z+SO9VIMRpPUbrU6VwP5cmjv3jtqeRfLDuYQuQ=,iv:sRuy9OW3QmQ/spTeOetGks7FOI9NIEsbfaiI014zKXc=,tag:Ht9xa9lHwDt88YuZRkmdPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
