apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Rg751M/1/xVm50u5dj/i8vI1Tl27wIaa4cc0JFWKS400+Dto,iv:joiHml/6z3IOO99r5ELsQTyPXasmyxzJsaYrcLwpN3M=,tag:j5jlMVO3lZmf0uZj0bgLiA==,type:str]
    credentials.json: ENC[AES256_GCM,data:OcjkF5Nu7zbfvUhhg05mu65q7rcp+n/wedhDzPrLYrooA1g3LrlLJx9ofxgL7eoUtl0KAHyMki3kGAn9YwDCTpa6V/dxTgn/ZX0dr0il4v9EsHOtE06Z2x0rUzeS1mVUGTUUKlYauQaIVCAQOmbEKVoZW4nJjBLH8EHiC63pfX9jk2stuZI8PjLx/N5ibZeMNeaNPWZXAGP+QDfK9ZEH07/XweYYPYTnccLy5B1Aug==,iv:5ZDxGtn4RKNB7aA6DqVY2LQVTojZqvOy1eMzS9ZRYVQ=,tag:bzoaTZ3SAMOvC3CfQ2TiVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eEJLSUMzWFRMci9YZnh3
            SndSaGRRQWhzVkIrL0U2bDM0dTQ5ekQwUXpNCkl0NENzQUZ2SmZiY2xMZVJoM0sw
            RVZqSnc1UTJicFBKWUtCMCtGOFcvQ28KLS0tIHAyRmgrNTF0NWpjQ201ZE5sU0tz
            MlY5VFluY2hXNURNUndoKzd5NjVIN1EKEh3FJgr4zH3sSIOd6G5NJ7v1r+vSw+WB
            OzGjWyY7XN98/10Vs0Vley3ojdp6Wbh8dABcG/xOw03ICgpjwXlnTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T15:39:07Z"
    mac: ENC[AES256_GCM,data:BcnNpkpmUbELdwMolETqz7HhVR6Gfc3Sy/l/Cx2ViCTLhUgvFenAMDUL60reXLdTR8RajOeZAJYovWJfzW1FUaZeRMkFkUM9lkgYq+iw7pmm5WeDEbO9oX1lS2rPp/MNoCh+4WfpCuInaPYQ6LM9gJc0Uvu0PdAmdUBKKLMkx10=,iv:y7d9x/SAdhiIcKl6pytzmvySQd1w47uYj9Azvk9X5Xc=,tag:ui3/L4ZY9xVY+boQwVb5lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
