---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earnapp1
  namespace: earn
  labels:
    app: earnapp1
spec:
  selector:
    matchLabels:
      app: earnapp1
      tier: frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: earnapp1
        tier: frontend
    spec:
      # renovate: registryUrl=https://github.com/Arno05/EarnApp-Docker
      containers:
        - name: earnapp
          image: arno05/earnapp:lite-1.294.218
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: 128Mi
            requests:
              cpu: "0.1"
              memory: 16Mi
          env:
            - name: EARNAPP_UUID
              valueFrom:
                secretKeyRef:
                  name: earnapp-secrets
                  key: earnappUuid1
      nodeSelector:
        network: internal
