apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-authelia-es
  namespace: &namespace databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: pg-authelia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_AUTHELIA_USER }}"
        password: "{{ .POSTGRES_AUTHELIA_PASS }}"
  dataFrom:
    - find:
        path: POSTGRES_AUTHELIA_
    - find:
        path: AWS_
