apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-lldap-es
  namespace: &namespace databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-connect
  target:
    name: pg-lldap-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .POSTGRES_LLDAP_USER }}"
        password: "{{ .POSTGRES_LLDAP_PASS }}"
  dataFrom:
    - find:
        path: POSTGRES_LLDAP_
