---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./tls.yaml
  - ./secrets.yaml
  - ./helmrelease.yaml
  - ./hpa.yaml
  - ./datasource
configMapGenerator:
  - name: blocky-config
    files:
      - ./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
