---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ./helmrelease.yaml
  - ./hpa.yaml
configMapGenerator:
  - name: blocky-config
    files:
      - ./config/config.yml
generatorOptions:
  disableNameSuffixHash: true
