---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lldap
  namespace: security
spec:
  maxReplicas: 3
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 90
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lldap
