apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:hyQyo3nqZYnVHGzP3RQ5S9UBmyGZDz3FyILmkTRGgFs=,iv:4IS5wpGR60Wo5fuONctBB5HeDWy6/fBqNxBEUdPObGY=,tag:XaXlmIGbm3UsLy9bpF8IVQ==,type:str]
    LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:WeEpOilz9WWt6Mm0k80=,iv:fuoAckdoOy7sdH0mSWHrEUY40w+Hq6DsZR6L0jDf1pw=,tag:6mHAF3aSaxSKeJ8fsknAOw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:j2ZQMn98vQ/BI5zCynD2OO42tugMRoD8DwddxJ9Kyg==,iv:REMBb0RUCAOc7xN5lRLTqrWkuvF8Nw9jDSo6k4vkGBA=,tag:weylm///I00lcHDLOG2h+A==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:i0UQUbAnY6IF3zIaOFG+FyQ=,iv:ZsCHaaadAoTlf7IUUz+jTqtI8+gucGFHrWPLk3saMcU=,tag:Bty/5pFvGSoTAyplpNWIBQ==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:8dutGLyZy4UauVt+/68yjGn16m3s+5MyAYvd6WFO,iv:AC0bQfnGk7Gz6R/RxsYrtbq1QUAATxmD06mWpJkM4lY=,tag:90OYwYrKn8a3e0lZSqF2Gg==,type:str]
    LLDAP_ADMIN_USERNAME: ENC[AES256_GCM,data:J5x5PlyTYdBO+bQVxPg=,iv:23UYeZQ+R1QcVO98tB91UaNw9qAvU4wdlW3IxHc3Wno=,tag:az7iQHyNU57vPspRSPanLQ==,type:str]
    LLDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:GQmoBboEGwF15OJckWwaRoe8Y7jNXlWJsDMlRlIV4A==,iv:Ym/RPFlIzecm/ZIoX6j4fy44hVJo2I/KQ25TOKpwbvY=,tag:oCgrEdivfp+wEstz2b828Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTEE2SC9BbDRaQ0tTbmhF
            M2tNOFFCSy9LM1p6QU83YkRleE95TWd0VEdjClhsY09JVklxb05xN1MrOEVET0Mx
            NUNpY01jaTFhQi80RnNxQmEwY3JIZjAKLS0tIGI1Z1BOZ1dtWDNLQVFhTDJXV3Q2
            dFpoWGl2OTBqK2dWM3hhSmlINDlodmcKvMYOHLhvqeYBDMhTa6NfQxmV/n9/qBke
            Ty5i0Y22spBQ7xohWijdNth+n/QMsQ74TpQ5d7qQccMNfRnXKmLQaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T14:33:02Z"
    mac: ENC[AES256_GCM,data:tlIPQ7Ssut3M6um6D/HRvmrVFEze08ATUg/Yy9t60DiGQ5KncVyg3hMDqbVDM7Bf2oADUJcd/TEQmWxuH/sHct4AZUSQoeBQNIlI3eu3p3UYucRERV5WMjBAIYiXcPRb5Q0tHeAA5Q1+Gyn3CWCs1O46VQFZDUq4S5a7Jh6Hzy4=,iv:Ovlm2oZnpK9r4o69luoTu+++UHNbwuJEPsYgwcHgZzA=,tag:/zp0JvXpeo5recvVncpxTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
