apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
stringData:
    #ENC[AES256_GCM,data:O6emUNIJ,iv:i0KtBcrSlrCeP2RMBKKgBGI8QYa9wlkhYDlWVy3+i7c=,tag:WR7bJIoZN/wCKBC5v3k/yQ==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:hyQyo3nqZYnVHGzP3RQ5S9UBmyGZDz3FyILmkTRGgFs=,iv:4IS5wpGR60Wo5fuONctBB5HeDWy6/fBqNxBEUdPObGY=,tag:XaXlmIGbm3UsLy9bpF8IVQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Q/ICyXNr9bX8k+6qV1W3U9Z3NsXp5Ky/H6l+A631zA==,iv:+25Bcurho3JVhDyaDHEtedQqiO121IYslIvmh8dL3Mg=,tag:3+xzwQQgpy1O9b372ltU9g==,type:str]
    LLDAP_USER_DN: ENC[AES256_GCM,data:aOZXNPYXDYHxKwfSytY=,iv:+LDSVdKNkCqaV05aUcPy/ZJpvHKfdayHQy7jtBypIEo=,tag:KBDFpjiQH+IvfbjZ8+h5EA==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:i0UQUbAnY6IF3zIaOFG+FyQ=,iv:ZsCHaaadAoTlf7IUUz+jTqtI8+gucGFHrWPLk3saMcU=,tag:Bty/5pFvGSoTAyplpNWIBQ==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:8dutGLyZy4UauVt+/68yjGn16m3s+5MyAYvd6WFO,iv:AC0bQfnGk7Gz6R/RxsYrtbq1QUAATxmD06mWpJkM4lY=,tag:90OYwYrKn8a3e0lZSqF2Gg==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:25mcAxlb9vUs4pnKCxrBIWrQpT9TfoL0lGPdB4RhNiQx7eo+pT4oXKGxqVTEWtwP8i1ZnuvEDWHyBD+JgulZOcCpJOPLAaw/wcjeO1wd1yIolPsWw6/PSi0M5HPJXlXA1e1iFQ==,iv:XXU6vayiR3fLUnSmGL3XTy9Tc8OEw1wdNqvey5qCtg0=,tag:xHVgEOuPuJi9lumUCK7bbA==,type:str]
    #ENC[AES256_GCM,data:xSab7rpEeR8T3E/upoA=,iv:qkN7wnyUt+3dPucmN/XbsfbH9Mtgga5/dTRssqdW8OM=,tag:5cYk+PWESEhO+aoctM/Qrg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:fSaOffw=,iv:12rh62DMkXzbHt1U5A984wk2urY8WP9M7NIWsez44HQ=,tag:A5f8Qv13EsojZQmXc8K5IQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:wx0VgorcJ9uEHdLiJi7HLd2o/iEmQ1WG+1KF+q4mf/dKlFldJpv4pbA=,iv:YP8NvpSoJXTGtRZbq1Uj9YBtP0zNE+YKk75TfTB0M8Y=,tag:HtcJdv8487VqFmRqECIeag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTEE2SC9BbDRaQ0tTbmhF
            M2tNOFFCSy9LM1p6QU83YkRleE95TWd0VEdjClhsY09JVklxb05xN1MrOEVET0Mx
            NUNpY01jaTFhQi80RnNxQmEwY3JIZjAKLS0tIGI1Z1BOZ1dtWDNLQVFhTDJXV3Q2
            dFpoWGl2OTBqK2dWM3hhSmlINDlodmcKvMYOHLhvqeYBDMhTa6NfQxmV/n9/qBke
            Ty5i0Y22spBQ7xohWijdNth+n/QMsQ74TpQ5d7qQccMNfRnXKmLQaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-17T16:36:23Z"
    mac: ENC[AES256_GCM,data:hgN9tAPGC09482QRfLc5tHBo9FoxPI+ylQsMrE5OrP8EE6e7DsxocEDUSD/5n+iKYZrLdbvJW9PXchUQ3jloFsu4OwolXfABdTLP4UCjCJgpMKTYubasg4nLcDZgR7w58+5ISOyJyMUq8IqFMwWzJaH0NKgeiCcit6iAiNC4PmI=,iv:DZ+XwYQX3ZrjuPpGRHIGDf3ryrfpoHdj5Ze5/zyJ5Ko=,tag:umFAfBcvqaN6ThBz/KxHOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
