apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
    namespace: security
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:hyQyo3nqZYnVHGzP3RQ5S9UBmyGZDz3FyILmkTRGgFs=,iv:4IS5wpGR60Wo5fuONctBB5HeDWy6/fBqNxBEUdPObGY=,tag:XaXlmIGbm3UsLy9bpF8IVQ==,type:str]
    LLDAP_LDAP_USER_DN: ENC[AES256_GCM,data:WeEpOilz9WWt6Mm0k80=,iv:fuoAckdoOy7sdH0mSWHrEUY40w+Hq6DsZR6L0jDf1pw=,tag:6mHAF3aSaxSKeJ8fsknAOw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:Q/ICyXNr9bX8k+6qV1W3U9Z3NsXp5Ky/H6l+A631zA==,iv:+25Bcurho3JVhDyaDHEtedQqiO121IYslIvmh8dL3Mg=,tag:3+xzwQQgpy1O9b372ltU9g==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:i0UQUbAnY6IF3zIaOFG+FyQ=,iv:ZsCHaaadAoTlf7IUUz+jTqtI8+gucGFHrWPLk3saMcU=,tag:Bty/5pFvGSoTAyplpNWIBQ==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:8dutGLyZy4UauVt+/68yjGn16m3s+5MyAYvd6WFO,iv:AC0bQfnGk7Gz6R/RxsYrtbq1QUAATxmD06mWpJkM4lY=,tag:90OYwYrKn8a3e0lZSqF2Gg==,type:str]
    LLDAP_ADMIN_USERNAME: ENC[AES256_GCM,data:J5x5PlyTYdBO+bQVxPg=,iv:23UYeZQ+R1QcVO98tB91UaNw9qAvU4wdlW3IxHc3Wno=,tag:az7iQHyNU57vPspRSPanLQ==,type:str]
    LLDAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:0GHLzA0awB8svcaa8vZVH4MXXMY+SgAiQa9GyKahTQ==,iv:D8MuJ11OeTVHedPPBopPmYBbizfpn3rwRkTBAIqJKcg=,tag:OF4o9QXBRYoLAGKwHgzr3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTEE2SC9BbDRaQ0tTbmhF
            M2tNOFFCSy9LM1p6QU83YkRleE95TWd0VEdjClhsY09JVklxb05xN1MrOEVET0Mx
            NUNpY01jaTFhQi80RnNxQmEwY3JIZjAKLS0tIGI1Z1BOZ1dtWDNLQVFhTDJXV3Q2
            dFpoWGl2OTBqK2dWM3hhSmlINDlodmcKvMYOHLhvqeYBDMhTa6NfQxmV/n9/qBke
            Ty5i0Y22spBQ7xohWijdNth+n/QMsQ74TpQ5d7qQccMNfRnXKmLQaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T13:34:02Z"
    mac: ENC[AES256_GCM,data:0kKA5u6M6EJKR6SQpx4GAUtH7HxyWq8nS2lUA8XHnGGNgQVpJYCS6iAOaTM33S0mAaJ9uYsr3uBQ2a9ynH8/MWW+j4FR4OOxy4MZJ/RVAvCQcYb4P2m/2da3UuxuWUeizUTVR02mtCAGQCaombvjS/OqykTGJi/YR/pquDGJ9OY=,iv:bMbBV/mptu04ijlC7KQKhIIQmjA1uE88keIlJdwHKYc=,tag:A6gKiFW7G/6xIJ6+ydAeFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
