---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dex
  namespace: networking
spec:
  releaseName: dex
  interval: 10m
  chart:
    spec:
      chart: dex
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.39.1
    ingress:
      enabled: true
      annotations:
        external-dns.home.arpa/enabled: "true"
        cert-manager.home.arpa/enabled: "true"
      hosts:
        - host: &host dex.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: dex-tls
    resources:
      requests:
        cpu: 50m
        memory: 200Mi
      limits:
        cpu: 200m
        memory: 200Mi
    # see https://github.com/dexidp/dex/issues/2082
    env:
      KUBERNETES_POD_NAMESPACE: networking
    config:
      issuer: https://dex.${SECRET_DOMAIN}
      connectors:
        - type: ldap
          id: ldap
          name: ldap
          config:
            host: ldap.${SECRET_DOMAIN}
            bindDN:
            bindPW:
      storage:
        type: kubernetes
        config:
          inCluster: true
      frontend:
        theme: coreos
        issuer: Milky Way
        issuerUrl: https://${SECRET_DOMAIN}
        logoUrl: https://imgur.com/Idzzln9.png
      expiry:
        signingKeys: 6h
        idTokens: 24h
      logger:
        level: debug
        format: json
      oauth2:
        responseTypes: ["code", "token", "id_token"]
        skipApprovalScreen: true
